### ISSUE TITLE
Scheduled reminders for Teams

### ISSUE THREAD

**Issue by ErikElkins** [integrations/microsoft-teams#10]
Will Teams see the Scheduled Reminders org level feature?

https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-scheduled-reminders-for-your-organization

**Comment by ashokirla** [comment]
@ErikElkins : Yes, we have plans to support schedule reminders. But it is not part of our Beta release which is planned in Aug'20. We might add this support sometime in next quarter.

**Comment by ashokirla** [comment]
We have rolled out our Public Beta. We will start work for supporting schedule reminders next month.

**Comment by ashokirla** [comment]
Keeping this issue open as we will be working on Schedule reminders this quarter.

**Comment by ashokirla** [comment]
@ErikElkins we are currently working on Schedule reminders feature and we would like to share the experience with you and get your feedback. Can you let us know if it is possible to have a quick call.

**Comment by ErikElkins** [comment]
@ashokirla ... absolutely! I'd love to give some early feedback.

I'm available on 9/30, 12pm CDT to 4pm CDT.

**Comment by ashokirla** [comment]
Great, can you please reachout to us at chatops@github.com so that I can block sometime.

**Comment by ashokirla** [comment]
@ErikElkins Schedule reminders is now available!!!

**Comment by mcg** [comment]
@ashokirla Is this rolling out? Not seeing it yet.

**Comment by ErikElkins** [comment]
That's awesome news @ashokirla! I look forward to a blog post to hear the fun details.

**Comment by lokeshram122** [comment]
can we subscribe to a particular GitHub team rather than a organization or a repository like slack notifications?
