### ISSUE TITLE
Github Enterprise

### ISSUE THREAD

**Issue by aga8541** [integrations/microsoft-teams#110]
The current application doesn't allow us to login to the github enterprise. Is it possible to add that new feature?

**Comment by gauravsaralMs** [comment]
@aga8541 : thanks for opening for this issue.

however we already have an issue https://github.com/integrations/microsoft-teams/issues/110 to track this request, hence closing this.

please participate in the issue created earlier.

**Comment by aga8541** [comment]
Thank you.!
