### ISSUE TITLE
Can't use @github to subscribe to channel

### ISSUE THREAD

**Issue by tmarkovski** [integrations/microsoft-teams#117]
**Describe the bug**
Cannot use the `@github` command to subscribe notifications in a specific channel. The option always opens the dialog to Create new Issue.
Bug happens on all apps, mobile, browser, Mac.

**To Reproduce**
1. Go to any channel
2. Type @github
3. Press Enter
4. Dialog shows up, instead link to the GitHub user.

**Expected behavior**
The `GitHub` user should be highlighted/selected and I can continue typing commands in the chat box.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser : Safari, Firefox

**Smartphone (please complete the following information):**
 - Device: iPhone

**Comment by gauravsaralMs** [comment]
@tmarkovski : can you please take a look at a similar reported issue and solution: https://github.com/integrations/microsoft-teams/issues/54#issuecomment-701140371 .

Please close the issue in case the solution provided works.

**Comment by tmarkovski** [comment]
Thanks @gauravsaralMs - the solution worked. Closing this as duplicate of #54
