### ISSUE TITLE
Query: Request status unchanged: Install Microsoft Teams for GitHub

### ISSUE THREAD

**Issue by rxa1031** [integrations/microsoft-teams#119]
Hello,

Unable to get access even after the GitHub admin approved below request:

![image](https://user-images.githubusercontent.com/18160755/117822208-f83dde80-b289-11eb-9154-e7a2a1901def.png)

I still observe the same status.

How to get this issue fixed on my side?

Please suggest.

Thanks,
Rajeev

**Comment by rxa1031** [comment]
Hello @gauravsaralMs ,

I am not aware why I still observe below, s there something that need to be done on GitHub PAge.
![image](https://user-images.githubusercontent.com/18160755/117913598-46d99000-b2ff-11eb-8bf4-5c5fe56e0cc8.png)

Please help me with steps to resolve both the concerns for which I have shared snippets.

Thanks,
Rajeev

**Comment by gauravsaralMs** [comment]
@rxa1031 : please look at the readme.md file of this repo
https://github.com/integrations/microsoft-teams/blob/master/Readme.md

Closing this issue because not a bug

**Comment by rxa1031** [comment]
Hi @gauravsaralMs 

The document content does not help resolve the below issue. The GitHub (private) repository owner did approve my request. But the below status still remains same:

![image](https://user-images.githubusercontent.com/18160755/118137775-3589a400-b423-11eb-9e01-be3b440c0699.png)

Regards,
Rajeev
