### ISSUE TITLE
new commit notification

### ISSUE THREAD

**Issue by chkwon** [integrations/microsoft-teams#12]
Thanks for working on this integration.  Is the new **commit** notification function planned?

**Comment by ashokirla** [comment]
@chkwon, Next week, we are rolling out public preview and this has support for commit notifications on main branch.

**Comment by chkwon** [comment]
@ashokirla Ahh that is awesome! Thanks for the update!

**Comment by ashokirla** [comment]
@chkwon Our [public beta ](https://github.blog/2020-09-10-announcing-the-github-integration-with-microsoft-teams/)is now available. Please try it out and share your feedback.
