### ISSUE TITLE
Query: Request status unchanged: Install Microsoft Teams for GitHub

### ISSUE THREAD

**Issue by rxa1031** [integrations/microsoft-teams#122]
Hi,
According to me my concern #119 is not resolved.

The GitHub (private) repository owner did approve my request. But the below status still persists and I cannot get past it:

![image](https://user-images.githubusercontent.com/18160755/118138115-944f1d80-b423-11eb-8bee-a978509a40c2.png)

Regards,
Rajeev

**Comment by rxa1031** [comment]
Hi @gauravsaralMs ,

The document you shared does not talk about how to get past above issue.

Regards,
Rajeev

**Comment by gauravsaralMs** [comment]
@rxa1031 : you will have to work with the repository/org owner so that repository/org owner approves your request.

**Comment by rxa1031** [comment]
@gauravsaralMs as informed before, the repository/org owner has already approved the request. But still the issue persists.

**Comment by gauravsaralMs** [comment]
@rxa1031 : can you confirm with org owner that they are able to see `Microsoft Teams for GitHub` under this Url:
https://github.com/organizations/<<org_name>>/settings/installations.   ?

**Comment by rxa1031** [comment]
Hello @gauravsaralMs ,

I have sent email to the GitHub owners for our repository. I shall get back an answer by Tuesday morning.

I'll get back to you with the findings.

Thanks,
Rajeev

**Comment by rxa1031** [comment]
Hello @gauravsaralMs ,

The above listed problem is resolved.

The owner had to approve the request twice in order to get past the observed issue.

Thanks,
@rxa1031

**Comment by gauravsaralMs** [comment]
Thanks for confirming @rxa1031 , please close the issue if your issue is resolved.
