### ISSUE TITLE
Dependabot & Teams Integration conflict wich each other

### ISSUE THREAD

**Issue by Leystryku** [integrations/microsoft-teams#126]
**Describe the bug**
The chat messages show a long list of unparsed HTML  tags when using both, Dependabot and the Teams Integration.

**To Reproduce**
1. Add Dependabot and Teams Integration to your Teams (both by Microsoft)
2. Wait for a Dependabot PR to come out
3. The chat notification from dependabot will be left unparsed

**Expected behavior**
I expected the message to not contain loads of unparsed ul tags etc

**Screenshots**
It basically looks like this
![image](https://user-images.githubusercontent.com/6385154/119465644-27e9ed80-bd44-11eb-86c8-93d6abe238c3.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Microsoft Teams
 - Version [e.g. 22] latest

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Samsung Galaxy S10
 - OS: [e.g. iOS8.1] Android
 - Browser [e.g. stock browser, safari] Teams
 - Version [e.g. 22] latest

**Additional context**
No additional information required.

**Comment by gauravsaralMs** [comment]
@apurva1112 : can you please look into this?

**Comment by apurva1112** [comment]
Hello @Leystryku . Thanks for pointing it out. This issue happened as dependabot uses HTML in PR body while we support only markdown as of now. We are looking more into this to support HTML as well in future.

**Comment by Leystryku** [comment]
Hello @apurva1112 , thanks. Sounds good. Since your team is looking into this in the future, should I leave the issue open for now or would you prefer if I closed it?

**Comment by apurva1112** [comment]
@Leystryku You may leave the issue open. We will close it if its no longer needed.
