### ISSUE TITLE
Unsubscribe does not work in some cases when issued inside the bot chat window

### ISSUE THREAD

**Issue by rxa1031** [integrations/microsoft-teams#136]
Hi,

Please check below image, even after issuing the unsubscribe <organization>/<project> command, the GitHub Chat bot is still reporting commits.

Please help fix this issue.

![image](https://user-images.githubusercontent.com/18160755/123375544-8b1aaa00-d5a6-11eb-84ac-a006daaec461.png)

Please help.

Thanks,
Rajeev

**Comment by gauravsaralMs** [comment]
@rxa1031 can you do a subscribe list and see if the output matches the input you are giving in unsubscribe command ?

**Comment by rxa1031** [comment]
Hello @gauravsaralMs ,

On executing _subscribe list_ I receive message:
_Subscribed to the following account_
_organization name_

Will I have to even issue command to unsubscribe from the Organization as well?

Regards,
Rajeev

**Comment by gauravsaralMs** [comment]
If you have subscribed to an org then you will have to unsubscribe from that org only..

can you share the outputs and commands you are sharing with aliasing the org name with something else, that would be much helpful to us to provide any clear feedback.

**Comment by gauravsaralMs** [comment]
please re-open the issue in case issue is still present

also please share the outputs and commands you are sharing with aliasing the org name with something else, that would be much helpful to us to provide any clear feedback.
