### ISSUE TITLE
cannot connect to github account from MS teams

### ISSUE THREAD

**Issue by lynnehansen** [integrations/microsoft-teams#139]
When executing the command @github signin with the github app in teams - nothing happens after clicking the 'connect to github account' button, and I see the error "[BotCardServiceImplememntation.buttonTrackOutcome()] Unsupported action type for adaptive card: signin" in developer tools.
Using teams through chrome in private mode, using a test account

**Comment by sanjeev9160** [comment]
@lynnehansen I have tried to repro by opening teams through chrome in private mode but didn't encounter any issue. I was able to signin without any issue.

Also, please ensure that you have added sites the can always use cookies in the privacy and security. refer: https://docs.microsoft.com/en-in/microsoftteams/troubleshoot/teams-sign-in/sign-in-loop#google-chrome

Also please share some more details like:
1. Version of chrome.
2. OS.

for reproing the issue. Thanks.

**Comment by alexander-levitsky95** [comment]
Hello, I also have the same issue. After clicking to the "Connect to GitHub account" nothing happens.

I'm using the MS Teams application on macOS.

**Comment by sanjeev9160** [comment]
@alexander-levitsky95 I tried to repro the issue on macOS but it works for me. 
Please do these steps to help us in seeing if there is a problem with msteams app.
1. Try to restart the Teams App and see if it works. Try to remove the teams cache and see if it works or not?
2. In case nothing works then Can you please try it in chrome and see if it is working or not? 

and share the details along with the MS Teams version macOS details. Adding snapshot/gif would be helpful. Thanks.

**Comment by lynnehansen** [comment]
I didn't have all the right cookie policies set - it fixed the issue for me
