### ISSUE TITLE
Cannot signin with desktop Teams app

### ISSUE THREAD

**Issue by jasonycw** [integrations/microsoft-teams#141]
**Describe the bug**
When I do signin, I was stuck at the a pop up about typing something

**To Reproduce**
1. Install GitHub
2. Type `signin`
    ![image](https://user-images.githubusercontent.com/4518597/125020606-bf648f00-e0ab-11eb-9422-5f79ccfae712.png)
3. Click connect gitHub account and enter the username password
    ![image](https://user-images.githubusercontent.com/4518597/125020641-d0ad9b80-e0ab-11eb-9b7a-77ef8e614bc8.png)
4. See this pop up
    ![image](https://user-images.githubusercontent.com/4518597/125020685-e02ce480-e0ab-11eb-904b-32605e39c4b0.png)
5. Type the code and nothing happen
    ![image](https://user-images.githubusercontent.com/4518597/125020731-f9359580-e0ab-11eb-910d-1c40de7a5e68.png)

**Expected behavior**
Login successfully?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Desktop app
 - Version: n/a
![image](https://user-images.githubusercontent.com/4518597/125020932-4b76b680-e0ac-11eb-9d86-c3e9890289e7.png)

**Additional context**
I have 2FA enabled for my GitHub account and the Teams is using a company email

**Comment by jasonycw** [comment]
If I try to use it in a channel, when I type on `@github `
![image](https://user-images.githubusercontent.com/4518597/125021311-f5eed980-e0ac-11eb-8434-82bdb97d79c1.png)
I see this pop up
![image](https://user-images.githubusercontent.com/4518597/125021344-04d58c00-e0ad-11eb-9489-d7de10226292.png)

**Comment by sanjeev9160** [comment]
@jasonycw I tried reproing the issue but not able to repro it. 

For channel: Can you please type @github and select the GitHub bot as you have done. Then it must appear like the pic below 
![image](https://user-images.githubusercontent.com/64134945/125025043-92aa7a80-e09f-11eb-8570-3a79496b4fe4.png)

And do a sign in, for me it is successful.
![image](https://user-images.githubusercontent.com/64134945/125024953-60991880-e09f-11eb-9dbd-4cb25d6d35a2.png)

In case if it does not work then please share the details of whether it works in chrome along with chrome version. 
Hope it helps. Thanks.

**Comment by jasonycw** [comment]
Hi @sanjeev9160 thanks for the quick reply, but I cannot tag GitHub in a channel

Like what I shown in https://github.com/integrations/microsoft-teams/issues/141#issuecomment-876894323
When I try to tag GitHub, it just throw a pop up asking me to signin.

![image](https://user-images.githubusercontent.com/4518597/125033105-77e8fd80-e0c1-11eb-9267-206ca7f2562a.png)
When I press space here, the following pop up
![image](https://user-images.githubusercontent.com/4518597/125033212-9cdd7080-e0c1-11eb-8925-b627c7200e05.png)

And I cannot signin through direct messaging the GitHub bot

**Comment by jasonycw** [comment]
I tried on browser version of Teams on Chrome 91.0.4472.124 (Official Build) (64-bit)

Get the same error on channel
![image](https://user-images.githubusercontent.com/4518597/125048461-87247700-e0d2-11eb-9fb1-1754b290d3e0.png)

But direct messaging it on Chrome works
![image](https://user-images.githubusercontent.com/4518597/125048574-a7eccc80-e0d2-11eb-9bda-11518d2f7440.png)

That mean only desktop app version not working?

**Comment by sanjeev9160** [comment]
@jasonycw You can try to restart the Teams and give a try once again.  Thanks.

**Comment by holytshirt** [comment]
Hi I'm having the same issue with trying to sign-in with github app.
I also have 2FA enabled on GitHub account and the Teams is using a company email.
I'm also a admin of multiple github organizations. 

OS: Windows 10
Browser: Desktop app
GitHubApp: Version 1.3

When I sign-in 
![image](https://user-images.githubusercontent.com/90132/125106072-1e8bc900-e0d7-11eb-9646-a548b79a9548.png)
Then connect
![image](https://user-images.githubusercontent.com/90132/125106154-3c592e00-e0d7-11eb-93cb-6c494e473613.png)
Then a code,  **there seems to be something missing in this sentence which may help with the issue** ```To finish linking your account with
, type```
![image](https://user-images.githubusercontent.com/90132/125106209-4bd87700-e0d7-11eb-9384-c02668bd59f0.png)
Then nothing ...
![image](https://user-images.githubusercontent.com/90132/125106302-66aaeb80-e0d7-11eb-817a-5bd6560ddef8.png)

Restarted/uninstalled/reinstalled many times.

**Comment by holytshirt** [comment]
I got  this working by, signing out of github and then using Teams in the browser to sign-in and then sign-in to github

**Comment by KaneTW** [comment]
Having the same issue. None of the workarounds seem to help.

**Comment by matt-forster** [comment]
I am also running into this issue with Teams Desktop, and I cannot load into teams in the browser (firefox).

I have OTP enabled and am getting exactly the same behaviour as listed above - not sure what to do with the number in the popup.

**Comment by aosunacon** [comment]
> I got this working by, signing out of github and then using Teams in the browser to sign-in and then sign-in to github.
> Doesn't work if I use the desktop app

Same here

**Comment by amardancandm** [comment]
Solution: 
1-Go to https://teams.github.com/
2-Use "Add to Teams"
It will ask you to open Team Application or Use Web - Choose "Use Web App Instead"
go to GitHub Bot and Sign-in 



I will not request for code anymore . 

If it works you will see You will see a Green check Mark:   
 ✅ amardancandm is now connected to @amardancandm

**Comment by matt-forster** [comment]
Using firefox - All I get is this modal over and over again when using the webapp;

![image](https://user-images.githubusercontent.com/3375444/128748009-0c0ccc9b-30f1-46fa-8d4a-c9da8a7f7425.png)

**Comment by sanjeev9160** [comment]
We are following up with the MS Teams team: https://github.com/OfficeDev/microsoft-teams-library-js/issues/630

**Comment by sanjeev9160** [comment]
For now to work around the signin issue. Please follow the steps mentioned below as a snapshot which will help in getting pass the issue.

![image](https://user-images.githubusercontent.com/64134945/130015238-52257591-d1bb-4968-ac5b-7a27047afe8b.png)

**[Channel Scope]**
![image](https://user-images.githubusercontent.com/64134945/130015363-3bfcd30b-6dec-48d0-8753-bf374f0dcdac.png)

**[Personal scope]**
![image](https://user-images.githubusercontent.com/64134945/130015571-0fdb34d6-42c5-4d7d-b65e-028da93bfe2f.png)

cc: @ashokirla

**Comment by sanjeev9160** [comment]
Closing the issue as we have mentioned the fix.
