### ISSUE TITLE
Team GitHub install

### ISSUE THREAD

**Issue by GCADM** [integrations/microsoft-teams#142]
**Describe the bug**
Not linking on the installation link you sent 
**To Reproduce**
Will check Teams Admin console if something not turned on 
1. Go to 'ms365 admin Teams to verify of GitHub is actually active '
2. Click on on link

**Expected behavior**
GitHub Teams install

**Comment by sanjeev9160** [comment]
@GCADM Can you please describe the bug as it is not clear from the description. 

Also, to install github app, please follow the documentation: https://github.com/integrations/microsoft-teams/blob/master/Readme.md#installing-the-github-integration-for-teams 
Thanks.
