### ISSUE TITLE
No Notifications appearing in Teams

### ISSUE THREAD

**Issue by simongh** [integrations/microsoft-teams#148]
**Describe the bug**
I can't see what's not working. We have a GitHub Organisation. The Teams app is installed & authorised for all repositories. All the repos are internal. I've installed the GitHub app in teams & signed it.
I can subscribe to the organisation, but no notifications are generated at all. If I try to subscribe to a repo, then I get an error that the repo was not found.
GitHub links are also not unfurled.

It appears some permission is missing somewhere, but there is no information on what that might be.

**To Reproduce**
1. Add GitHub to Teams
2. Install Teams App to GitHub
3. Subscribe to owner

**Expected behavior**
Expect notifications to appear in Teams

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser n/a
 - Version n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
The intergration worked briefly back in May for 1 week & hasn't worked since.

**Comment by gauravsaralMs** [comment]
@simongh this seems to be a SAML issue.

**Quick thing to try**
- can you try this : https://github.com/integrations/microsoft-teams/issues/58#issuecomment-702978337

**Ask** 
- can you run `@github debug` command and share the output

@apurva1112 can you look into this?

**Comment by simongh** [comment]
It seems signout and signin fixed it. thanks for your help

**Comment by simongh** [comment]
I've not tested the subscriptions yet, but it's unfurling links again

**Comment by simongh** [comment]
All tested and subscriptions work too.
