### ISSUE TITLE
I can't create an issue in Teams

### ISSUE THREAD

**Issue by gaetan-nfcom** [integrations/microsoft-teams#152]
When i click on the github's image, i fill in the fields
![Capture](https://user-images.githubusercontent.com/77383371/129200482-f5877cd9-804d-4cab-819f-d4e65bc79f52.PNG)

there is this message : 
![Capture](https://user-images.githubusercontent.com/77383371/129200812-8852d996-12ca-471a-9d61-3dc6732ea145.PNG)

but i have already configured my github for teams.

Someone have an idea how to solve that ?

**Comment by gauravsaralMs** [comment]
@gaetan-nfcom : please click on the install-app flow and make sure to select the org where you want to create the issue.
also make sure the the input is correct..

like for issue https://github.com/gauravsaralMs/devops-tasks/issues/686

I entered `gauravsaralms` as owner and `devops-tasks` as the repo


@sanjeev9160 to look further at this.

**Comment by gauravsaralMs** [comment]
@gaetan-nfcom : if you are able to create issue from GitHub now, please update and close the issue.

**Comment by gaetan-nfcom** [comment]
Thank you but for the org is good but i have a doubt on the input who concern the repository name.

There is not auto completion and i don't know in what form i must write in the inputs.

Warning your link doesn't works :)
![Capture](https://user-images.githubusercontent.com/77383371/129202794-e5ed6e73-1f5e-424a-9697-dbd8e852256c.PNG)

**Comment by gauravsaralMs** [comment]
> There is not auto completion and i don't know in what form i must write in the inputs.

Yes auto-complete is not present. we can take that as a feature request.

for issue https://github.com/gauravsaralMs/actionPlayGround/issues/1

the input should be like the below
![image](https://user-images.githubusercontent.com/43203065/129205212-fc88d7b3-4a59-4b77-866e-c7aa41f5446a.png)

**Comment by gaetan-nfcom** [comment]
> > There is not auto completion and i don't know in what form i must write in the inputs.
> 
> Yes auto-complete is not present. we can take that as a feature request.
> 
> for issue [gauravsaralMs/actionPlayGround#1](https://github.com/gauravsaralMs/actionPlayGround/issues/1)
> 
> the input should be like the below
> ![image](https://user-images.githubusercontent.com/43203065/129205212-fc88d7b3-4a59-4b77-866e-c7aa41f5446a.png)

Ok Thank you i have try this with my org and my name like you say but it still does not work.

**Comment by gaetan-nfcom** [comment]
> > > There is not auto completion and i don't know in what form i must write in the inputs.
> > 
> > 
> > Yes auto-complete is not present. we can take that as a feature request.
> > for issue [gauravsaralMs/actionPlayGround#1](https://github.com/gauravsaralMs/actionPlayGround/issues/1)
> > the input should be like the below
> > ![image](https://user-images.githubusercontent.com/43203065/129205212-fc88d7b3-4a59-4b77-866e-c7aa41f5446a.png)
> 
> Ok Thank you i have try this with my org and my name like you say but it still does not work.

the same message appears 
![Capture](https://user-images.githubusercontent.com/77383371/129205884-51c1c3c3-39d9-4f22-aaf0-c77721e4230f.PNG)

**Comment by gauravsaralMs** [comment]
@gaetan-nfcom ... 
can you share

- screen shot of https://github.com/settings/installations
- screen shot of the issue creation dialog once you have added all the data in it

**Comment by gaetan-nfcom** [comment]
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/77383371/129206467-2e28567d-e743-43d6-bbd6-060de52b2f46.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/77383371/129206475-c745e49a-c785-4cdb-90c6-3f5a2133f86a.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/77383371/129206479-0a0ac899-aa24-47cb-b91a-db7b465e909e.png)

**Comment by gauravsaralMs** [comment]
@gaetan-nfcom I want to look at the https://github.com/settings/installations. (installed app tab)

if you have installed the app then it should show up like this

![image](https://user-images.githubusercontent.com/43203065/129206927-aa512ff5-0030-427b-a0b4-c1940b2305f1.png)

**Comment by gaetan-nfcom** [comment]
![Capture](https://user-images.githubusercontent.com/77383371/129207121-319be70d-a4c1-46d8-9ec9-ec248e5d09ba.PNG)

**Comment by gauravsaralMs** [comment]
@gaetan-nfcom This means that app is not installed...

if you click on the install app button
![Capture](https://user-images.githubusercontent.com/77383371/129200812-8852d996-12ca-471a-9d61-3dc6732ea145.PNG)
it will take it to you
https://github.com/apps/microsoft-teams-for-github/installations/new

there you can select your app/ user name and things should start to work for you

**Comment by gaetan-nfcom** [comment]
Okay i have already do all you say at the beginning and i can subscribe and when someone of my org to do an issue from github i am notified

**Comment by gaetan-nfcom** [comment]
I'm going to try to close post from github and i receive this just now : 
![Capture](https://user-images.githubusercontent.com/77383371/129209117-05112fbb-a763-414f-a053-9641a57a3fb5.PNG)

**Comment by gauravsaralMs** [comment]
Is this what you are trying?
please confirm the inputs except for title and desc

![image](https://user-images.githubusercontent.com/43203065/129209458-e076ed7e-6f50-4978-bcca-a6d3cc7fcef6.png)

**Comment by gaetan-nfcom** [comment]
> Is this what you are trying?
> please confirm the inputs except for title and desc
> 
> ![image](https://user-images.githubusercontent.com/43203065/129209458-e076ed7e-6f50-4978-bcca-a6d3cc7fcef6.png)

Okay thank you i can create an issue it was my fault i put my first name in place of nfcom

**Comment by gaetan-nfcom** [comment]
It works thank you :)

**Comment by gauravsaralMs** [comment]
> > Is this what you are trying?
> > please confirm the inputs except for title and desc
> > ![image](https://user-images.githubusercontent.com/43203065/129209458-e076ed7e-6f50-4978-bcca-a6d3cc7fcef6.png)
> 
> Okay thank you i can create an issue it was my fault i put my first name in place of nfcom

Any suggestion if we can change something to make the experience better?
would changing Owner to Owner/Organization help ?

**Comment by gaetan-nfcom** [comment]
> > Okay thank you i can create an issue it was my fault i put my first name in place of nfcom
> 
> Any suggestion if we can change something to make the experience better?
> would changing Owner to Owner/Organization help ?

Yes i think it would be better :)

**Comment by gaetan-nfcom** [comment]
> > > Okay thank you i can create an issue it was my fault i put my first name in place of nfcom
> > 
> > 
> > Any suggestion if we can change something to make the experience better?
> > would changing Owner to Owner/Organization help ?
> 
> Yes i think it would be better :)

And it's possible but i think it's a  many feature :  
1. add the possibilites of choose assignment to a person  
2. Assign it to a task
3. drop-down list with all the repos
