### ISSUE TITLE
Is the Github app login feature integrated with SAML SSO ?

### ISSUE THREAD

**Issue by MindyTai** [integrations/microsoft-teams#155]
**Describe the bug**
My Enterprise Github uses SAML SSO to login. But when I login, the Github app doesn't show the SSO login page.

**To Reproduce**
1. Go to Github app and type **signin** command
2. Click on **Connect Github account**
3. login page pop up

**Expected behavior**
The app should show SSO login page.

**Screenshots**
<img width="431" alt="Screen Shot 2021-08-18 at 2 43 24 PM" src="https://user-images.githubusercontent.com/7506495/130004454-23cd5f9e-5ae3-407f-a759-90dbcc11dc70.png">

**Desktop:**
 - OS: MacOS
 - Software: Teams

**Additional context**
The README says the app supports Github Enterprise, so I wonder how to figure this out. Did I misunderstand something? Thanks for reading my report.
![Screen Shot 2021-08-19 at 11 22 02 AM](https://user-images.githubusercontent.com/7506495/130004515-bf1b8de2-0e33-4661-b761-2d394c413203.png)

**Comment by gauravsaralMs** [comment]
👋🏼  please take a look at https://stackoverflow.com/questions/62459585/what-is-the-difference-between-github-enterprise-cloud-and-on-premise#:~:text=The%20basic%20difference%20is%20that,You'll%20find%20more%20here.  for difference between github enterprise 'cloud' and 'On premise'

if you are using enterprise 'cloud' (means your github organisation is somewhere github.com/**** ) then the app is supported.

else there is already a feature request open https://github.com/integrations/microsoft-teams/issues/27

**Comment by MindyTai** [comment]
@gauravsaralMs, thanks for your response. I'm waiting for GHES support too.
