### ISSUE TITLE
Tagging GitHub automatically creates an issue

### ISSUE THREAD

**Issue by tbelknapsgs** [integrations/microsoft-teams#156]
**Describe the bug**
Recently installed this integration. I attempted to subscribe to a repository by issuing the following command:
`@github subscribe tbelknapsgs/visualize`

If I paste that command into the window, nothing happens. If I just type @github and hit the space bar, a new window automatically pops up asking to create a new issue in my repository?

**To Reproduce**
1. Open a new chat window
2. type "@github"
3. Add one space

**Expected behavior**
I should be able to continue typing to issue the subscribe command.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac Catalina
 - Browser: Chrome 
 - Version: Version 92.0.4515.131 (Official Build) (x86_64)

**Comment by gauravsaralMs** [comment]
@tbelknapsgs 

- the bot needs to be added to team, please see the below comment for details
https://github.com/integrations/microsoft-teams/issues/54#issuecomment-701140371
- the way teams work it will not let command copy/paste work.. so you will still have to type `@github` but after adding it to team you should be able to issue command (like subscribe)

**Comment by gauravsaralMs** [comment]
@tbelknapsgs : did the above comment helped you?

**Comment by tbelknapsgs** [comment]
Yes, I believe it does, thank you.
