### ISSUE TITLE
Cannot subscribe enterprise org with SSO enabled

### ISSUE THREAD

**Issue by srivatsamarichi** [integrations/microsoft-teams#161]
**Describe the bug**
Cannot subscribe enterprise org with SSO enabled.

**To Reproduce**
1. Go to 'Apps'
2. Click on 'GiHub' to install.
3. Scroll down to 'subscribe'
4. See the below screenshot for reference.

**Expected behavior**
Cannot subscribe to the enterprise org which has SSO enabled. There is no option to subscribe to the enterprise org with SSO enabled. Does this support at first?

**Screenshots**
![2021-09-03_11-17-46](https://user-images.githubusercontent.com/13433045/131956612-6977cac6-3a18-49cd-8c2f-30de17456791.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 Enterprise]
 - Browser [e.g. chrome]
 - Version [e.g. 21H1]

**Smartphone (please complete the following information):**

**Additional context**
How do I get subscribed to the enterprise orgs with SSO enabled? This will help us to expedite the issues, PRs etc via team's app. Looking forward to the successful integration.

**Comment by gauravsaralMs** [comment]
@srivatsamarichi  this seems to be a SAML issue.

**Quick thing to try**
- can you try this : https://github.com/integrations/microsoft-teams/issues/58#issuecomment-702978337

**Ask** 
- can you run `@github debug` command and share the output

**Comment by gauravsaralMs** [comment]
@srivatsamarichi Gentle Ping

**Comment by gauravsaralMs** [comment]
@srivatsamarichi please reopen the issue and let us know in case issue is still happening

**Comment by wrobb** [comment]
I had this same issue today and the signout/signin suggestion fixed it. Thanks!
