### ISSUE TITLE
Url is tampered in preview card when the link unfurls in teams

### ISSUE THREAD

**Issue by Abhiram219** [integrations/microsoft-teams#179]
**Describe the bug**

When the Url is unfurled in teams by using [link unfurling](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?tabs=dotnet), in preview mode & is being converted to &amp; As a result our page is beraking.

Example: When I paste a URL 'https://www.abc.com/ab?c=d&e=g' this url is being converted to  'https://www.abc.com/ab?c=d&amp;e=g'

**To Reproduce**
1. Add compose extensions in manifest and make unfurling work in teams.
2. Paste a valid link and minimize it into preview mode and send it.
3. On clicking the preview card it takes to a new tab with tampered URL.
4. Tampered URL can be found in the tooltip on hovering the preview card.

**Expected behaviour**
 The expected behaviour is to open with the pasted URL without being tampered

**Screenshots**
<img width="634" alt="Screenshot 2021-12-02 at 10 36 00 AM" src="https://user-images.githubusercontent.com/60126553/144361214-d4d8b14d-d11a-4304-a6d4-2d8688a5917f.png">
 
-- Above described behaviour can be seen in the image

**Desktop (please complete the following information):**
 - OS: [Mac] ( could be an issue in other OS as well)
 - Browser [ chrome, safari]
 - Version [all]

**Comment by gauravsaralMs** [comment]
@Abhiram219 this app/repo handles unfurl only for urls which are in github.com domain.

You can report your issue to MsTeams.
[Instructions](https://answers.microsoft.com/en-us/msteams/forum/all/how-do-i-report-problems-with-microsoft-teams/d3aef6f9-9f29-4f4f-ab03-830b2d0f9bcd)
