### ISSUE TITLE
Add support for Enterprise Managed Users

### ISSUE THREAD

**Issue by mcurole** [integrations/microsoft-teams#185]
**Is your feature request related to a problem? Please describe.**
We are implementing [GitHub Enterprise Manager Users - emu](https://github.com/integrations/microsoft-teams#future-work) and the teams app doesn't not work with the login required for EMU

**Describe the solution you'd like**
Update the login process to allow one to link with an EMU account.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by jdesulme** [comment]
While it's not readily apparent you can pass in your EMU handle and it will gray out the password field and change the button to login with your IDP. That should than allow you to connect to it.

**Comment by mcurole** [comment]
Thank you. I actually discovered this on my own and forgot I had this issue out there.

**Comment by dmeatte-aq** [comment]
@jdesulme , @mcurole , I'm also trying to connect an EMU with the Teams integration. What do you mean by pass in the EMU handle? Thanks.

**Comment by mcurole** [comment]
Actually, I ended up just using my EMU ID and it redirected me properly to my IdP

**Comment by dmeatte-aq** [comment]
@mcurole, thanks. The issue was I use the desktop client. Once I used the web browser, it was able to use my existing auth tokens to set up the account. The connection now works in the desktop and web browser client.
