### ISSUE TITLE
Microsoft Teams Apps not listing on Developer Portal

### ISSUE THREAD

**Issue by dmoorjmalani** [integrations/microsoft-teams#186]
**Describe the bug**
I uploaded Sample Teams App in the Developer Portal after adding a tab to a site. And the listing that you see stopped coming up, every time i add a new app, it just vanishes and never comes up in the list. When i open the Developer Portal in browser i see  [ https://dev.teams.microsoft.com/amer/api/appdefinitions/my/?pageNumber=1](url) erroring in 500. See the screen shot below,
![TeamsDeveloperPortal](https://user-images.githubusercontent.com/6703440/147259541-2d1cbe0e-efad-4d3d-b612-b1307bb824fa.PNG)
I have tried finding the apps in question using PowerShell commands (Get-TeamsApp)  but i can't.
When i go to Tools -> Identity platform management i see the apps
![image](https://user-images.githubusercontent.com/6703440/147260060-12b0636d-c4c8-4016-af65-b99e08f8350c.png)

About Custom App Development policies,
We have Custom App turned on in Org-wide settings (earlier it was off)
Under Permission Policies the Custom App has recently been enabled
Under Setup Policies the Upload Custom Apps is blocked.

I have tried setting these setting on and off, but it is not working. Point to note that, i was able to create/modify apps before I changed first two settings.

**Comment by ashokirla** [comment]
@dmoorjmalani We are a GitHub team that owns GitHub integration with MS Teams. This repo is for sharing feedback for GitHub app in Microsoft Teams. I think this issue should be reported to Microsoft Teams platform.
