### ISSUE TITLE
Adaptive card not rendering properly on Android

### ISSUE THREAD

**Issue by DhavalThumar** [integrations/microsoft-teams#195]
**Describe the bug**
Adaptive card v1.5 not properly rendering on Android's Team App version 1416/1.0.0.2021206203 release. The same adaptive card is properly rendered on 1416/1.0.0.2021195305 version

**Screenshots**
Expected Result (Adaptive card working properly on lower Team's app version on Android
![Expected](https://user-images.githubusercontent.com/23481718/151007534-b71d2d04-d85a-4c00-82ad-869e1103370c.png)

Unexpected Result (After updating Teams app from Play store getting this result)
![NotExpecting](https://user-images.githubusercontent.com/23481718/151007800-7d433e3e-876c-4db7-a6d0-a7b095d6f8e3.png)

**Comment by ashokirla** [comment]
@snankani Can you get the DRI look into this issue.
