### ISSUE TITLE
Microsoft Teams runs much slower on Linux

### ISSUE THREAD

**Issue by Niedzwiedzw** [integrations/microsoft-teams#206]
I love Microsoft and Microsoft Teams, but it runs much worse on linux and I need to use linux cause I'm developing a cross platform apps in C#... 
I think the cause is that it doesn't use Webview2 implementation on Linux. 
This is the related issue https://github.com/MicrosoftEdge/WebView2Feedback/issues/645

**Comment by ashokirla** [comment]
Hi @Niedzwiedzw, We are a GitHub team that owns GitHub integration with MS Teams. This repo is for sharing feedback for GitHub app in Microsoft Teams. I think this issue should be reported to Microsoft Teams platform.

**Comment by Niedzwiedzw** [comment]
@ashokirla thank you, could you point me to the right direction? where could I report this problem?
