### ISSUE TITLE
@ mentions support

### ISSUE THREAD

**Issue by JohnBertelsen** [integrations/microsoft-teams#210]
@ mentions support - notify the user when they are assigned an issue, added as a reviewer for PR or Deployment, someone mentioned you in a comment or description which is posted to the channel/personal chat via subscription.

Can we have this please

**Comment by svanschuyver** [comment]
I would love to see this as well

**Comment by aaron-kruse** [comment]
It looks like this has been added at some point: https://github.com/integrations/microsoft-teams?tab=readme-ov-file#mentions

I'm not sure when this was added and why there wouldn't have been some sort of "official" response/update to this issue when it happened, but I just thought I'd give an update in case you weren't already aware (and for anyone else that might come across this).

**Comment by JohnBertelsen** [comment]
Looks like this is more or less fixed in the feature @aaron-kruse posted. 

I would have hoped for the option to subscribe to my work organization, but only receive messages with my @mentions in. 
In my experience the teams chat, gets cluttered quite fast.

But oh well, this will have to do.
