### ISSUE TITLE
Theme not applying to video calls

### ISSUE THREAD

**Issue by ryantho66** [integrations/microsoft-teams#211]
**Describe the bug**
Theme does not properly apply to video calls. The border, chat, etc are all dark even when on the default theme.

**To Reproduce**
1. Set theme to default
2. Start a video call

**Expected behavior**
Video call should match theme of Teams

**Screenshots**
![image](https://user-images.githubusercontent.com/37420986/172712094-e2288463-7ded-4bdf-9249-25c7dcc7a2a3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, 21H1
 - Version 1.5.00.11163 (64-bit)

**Additional context**
This genuinely hurts my eyes to look at most of the time, and I'd imagine others have the same issue.

**Comment by aasiddiq** [comment]
Hi @ryantho66  
We are a GitHub team that owns GitHub integration with MS Teams. This repo is for sharing feedback for GitHub app in Microsoft Teams. This issue should be reported to Microsoft Teams platform.
