### ISSUE TITLE
Manifest parsing fails 

### ISSUE THREAD

**Issue by RaiAmanRai** [integrations/microsoft-teams#216]
On uploading a custom built, I get hit with "manifest parsing failed" while another manifest with just a different app name passes manifest parsing.

Even the failed manifest passes after a couple of 100 tries.

Even, when I try to create my own app through teams, it fails the auto-generated manifest!!

I don't understrand, if I am doing something worng or is there a bug in teams.

**Comment by aasiddiq** [comment]
@RaiAmanRai I believe you are trying to upload a manifest on Microsoft Teams to create a Teams app, if so, this is not the right repo for this. This repo is for GitHub and Microsoft Teams integration, you can read more [here](https://github.com/integrations/microsoft-teams#help-your-teams-communicate-and-collaborate-better).

**Comment by RaiAmanRai** [comment]
Hi @aasiddiq thanks for pointing out, could you please help me with the correct repo where I can raise this issue.

**Comment by aasiddiq** [comment]
@RaiAmanRai Not exactly sure but you can try reaching out to [Microsoft Teams developer support](https://docs.microsoft.com/en-us/microsoftteams/platform/)?

**Comment by RaiAmanRai** [comment]
@aasiddiq thanks, I will go ahead and close this issue.
