### ISSUE TITLE
Integration don't display markdown style

### ISSUE THREAD

**Issue by rahfaeu-bk** [integrations/microsoft-teams#223]
Normally I use markdown checkboxes to remember code review tasks, and that integration ignore the markdown style when show updates card on Teams.

There is a way to able this integration to show the markdown style on pull request cards updates, as viewed on github interface?

**Comment by davereid-pfg** [comment]
I think this would be a duplicate of https://github.com/integrations/microsoft-teams/issues/169

**Comment by rahfaeu-bk** [comment]
You're right, I will close this issue.
Thanks
