### ISSUE TITLE
I should figure out how this works git hub thing works. 

### ISSUE THREAD

**Issue by 1DTSzumski** [integrations/microsoft-teams#234]
I spent a hour in power apps sounds strange script would have been easier.  Them power apps just bit much for me. I open wall tried manipulate the script. I gave up on that over a hour formatted 6 fields finically I just gave up. Went back to adding a degrees sign into tables in Excel I forgot how. Forums doing trig I knew I forgot but not all that. I dug up old workbooks It was easy not really repetitive. I did like half million it just looks better and is quarriable with trig.   I never liked trig gives me a headache.  
I ran across nice API I got sidetracked need to make certificates. I wanted to make a app in power apps to hard I don't believe what they call apps. Making them for years. I want to tie everything together one app going keep the seemingly useless numbers.  Be like spots put post in a canvas the tent a tapestry. I want to use the Cassini overlay  the Hellenistic with the transparency like ghost is nice but the Cassini deeper richer more texture. Like Astrology its a very old beautiful map. I love old maps are a mixture or art and mathematics, science,  geometry. The art of cartography. Like Astrology a beautiful map but very old. Navigationally as for accuracy well the Zodiac is few thousand years out of date. Goodbye World I should do the hello world thing.

**Comment by aasiddiq** [comment]
Closing as not relevant to GitHub MS teams integration
