### ISSUE TITLE
Update on - Schedule reminders updates

### ISSUE THREAD

**Issue by andresako** [integrations/microsoft-teams#238]
Hello team, 
Any update on the below? 

> Schedule reminders updates - Provide advanced controls for schedule reminders backed by a easy to use UI and remove administrator requirement for scheduling a reminder. We are planning to rollout this support by end of August, 2022.

It is something that we are waiting for in my team :)

**Comment by ashokirla** [comment]
This feature is now shipped. Please refer to the documentation for more details.

Thanks.
