### ISSUE TITLE
Reviewers section is not updated when changed on a pull request on GitHub

### ISSUE THREAD

**Issue by bradcutshall** [integrations/microsoft-teams#241]
**Describe the bug**

When a reviewer is added to a pull request, the "Reviewers:" section on the GitHub message in Microsoft Teams is not updated to reflect the changes.

**To Reproduce**

1. Ensure your channel connector is subscribed to the repository desired with pulls.
2. Create a new pull request in GitHub.
3. Notice the GitHub connector notifies the channel as desired.
4. On GitHub, add a "Reviewer" to the pull required.
5.a. Actual: "Reviewers:" in teams is not updated.
5.b. Expected: "Reviewers:" in teams is updated with the newly added/removed reviewer.
6. Complete the pull request.
6.a Notice the pull request's status is updated, but the reviewers is still not updated.

**Expected behavior**

When a reviewer is added/removed to the pull request on GitHub, the connector should update the "Reviewers:" with the reviewers assigned in the Microsoft Teams message.

**Desktop (please complete the following information):**
 - OS: MacOS Monterey Version 12.6
 - Browser: Edge Version 105.0.1343.50
 - Microsoft Teams: (MacOS) Version 1.5.00.22362 

**Additional context**

I tried setting up the connector as well as viewing messages on both the native MacOS app, and within the Edge browser, both environments exhibited the same behavior.

**Comment by bradcutshall** [comment]
Channel connector /github connector is the tool that allows you to mention GitHub in the Microsoft Teams channel using @GitHub, ie. @GitHub subscribe <org>/<repo>

Example image:
<img width="878" alt="image" src="https://user-images.githubusercontent.com/110041485/192896167-ce24f736-e117-4997-b9d7-f39f33f93868.png">

**Comment by sanjeev9160** [comment]
@bradcutshall Do you see it happening for all the PR notifications cards? As I am just guessing this may be due to some transient issues. Meanwhile I will try to check if there are any issues from our side. Thanks.

**Comment by bradcutshall** [comment]
@sanjeev9160 I don't know what changed, but as of today (3 Oct 2022) the reviewer is being assigned and updated correctly.
