### ISSUE TITLE
"Could not find resource" for GHEC EMU repo

### ISSUE THREAD

**Issue by fuhuifang** [integrations/microsoft-teams#242]
Hello, our repo was just migrated into GHEC EMU, and I was trying to set up notifications on Teams. I did `@Github subscribe <owner>/<repo>`, but it returns
```
Could not find resource <owner>/<repo>.
Please check to make sure the spelling of the resource was correct and that you have access to the resource in GitHub.
```
Is GHEC EMU supported?

**Comment by ashokirla** [comment]
@sanjeev9160 can you look into this issue.

**Comment by ashokirla** [comment]
@fuhuifang Can you try to logout of the app @github signout and then try signing in again.

**Comment by fuhuifang** [comment]
Where can I sign out? I think the issue might be we need two github accounts - one for public github, and another one with Microsoft SSO..

**Comment by fuhuifang** [comment]
Not sure if this is the correct way, but I was able to set up the connection using "Github Enterprise" app on Teams

**Comment by ashokirla** [comment]
@fuhuifang We dont own GitHub Enterprise app. And it is going to be replaced once we bring in first class support for GHES integration. You can signout by running a command from your channel or github app personal chat. 

Do you have two different usernames (GHEC and EMU)? In that case, can you signin with your GitHub EMU username. You should get an option to login with your Identity provider. Signin is handled by GitHub platform and we dont do any customisations from the app side.

**Comment by fuhuifang** [comment]
Thanks @ashokirla, yes I was able to login with my EMU account. We do have two usernames. 

Really appreciate all of your help!
