### ISSUE TITLE
Checks not updated to reflect data on GitHub after a failed check

### ISSUE THREAD

**Issue by bradcutshall** [integrations/microsoft-teams#252]
**Describe the bug**
A unit test check failed during a merge and the checks represented this correctly in teams by showing 0/1. Once the unit tests check was resolved on GigHub, the checks in teams did not update to show 1/1, instead it still showed 0/1.

**To Reproduce**
- Made PR on GitHub
- Card shows up in teams
- Test (check) on GitHub finishes and fails
- Pushed new changes to fix the failing test/check
- PP still unclaimed by reviewer and test checks now pass
- Teams card for the pr does not get updated and stills says failing test/checks
- Reviewer assigns themself to pr and the card finally updates to saying test/checks are passing at the same time it updates to add the reviewer

**Expected behavior**
The checks should be updated on teams with the checks are updated in GitHub

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.6
 - Version: 1.5.00.26358

**Comment by aasiddiq** [comment]
@bradcutshall thank you for raising this issue. I tried to repro this but could not. 
I followed your steps given, 
- Raised a PR
- check fails
- card shows failed check
- push new changes
- check passes
- same is updated in the card

Could you confirm again if you are still seeing this?
