### ISSUE TITLE
Team selection for Scheduled Reminder does not work

### ISSUE THREAD

**Issue by nooblucker** [integrations/microsoft-teams#254]
**Describe the bug**
When creating a scheduled reminder for defined teams, the team selection dropdown does not work properly. 

**To Reproduce**
0. Make sure your orga has > 360 teams
1. Go to a teams channel
2. Write @github schedule <orga>
3. Click on "Create reminder"
4. Choose "Only selected teams"
5. Try to search for your team - you do not get any results, but an error message
6. Remove the typed letters
7. When all letters are removed, you get a list with teams

**Expected behavior**
I would expect a list with teams that are matching the search term. 
The list should be sorted alphabetically.
ALL the teams should be available. It seems the number of teams is limited to 100 or so.
It is not possible to edit the teams selected.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/3714349/198303180-e700c126-12a1-403d-a408-98e1c670b690.png)

![grafik](https://user-images.githubusercontent.com/3714349/198304301-e66d7c28-1ef6-4997-a9dc-0b623f5a5f38.png)

![grafik](https://user-images.githubusercontent.com/3714349/198304434-1e2fd771-582f-4970-a3f7-9dab80b22ff8.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Microsoft Edge Version 106.0.1370.47 (Official build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nikhilgarg1047** [comment]
Hi @nooblucker - If the _All teams_ is selected, max. 100 teams are shown. For _Only selected teams_ option, I'm not able to reproduce the issue with an org having 400 teams. Can you please provide more details about the error or time you've tried the scenario so that I can check in the logs at my end?

**Comment by nooblucker** [comment]
> Hi @nooblucker - If the _All teams_ is selected, max. 100 teams are shown. For _Only selected teams_ option, I'm not able to reproduce the issue with an org having 400 teams. Can you please provide more details about the error or time you've tried the scenario so that I can check in the logs at my end?

Hi, sorry I don't get it. If all teams is selected, I do not need to query any team, because I want all teams. So I am not sure what you mean with it being limited to 100 if all teams is selected. So the bug report refers to the case when "only selected teams" is selected.

However what I see is that neither the filtering nor showing all available teams is working properly as it can be seen on the screenshots. If I type some letters, I do get 0 results. If I remove the letters again, I get only 100 teams instead of 360. the problem therefore seems to consist of several (individual?) problems. 

1. getting no results when typing letters for existing teams
2. not getting all available teams in the list 

It affects all employees in our org, not only me. Btw. I need to comment here with my private account because my Org is configured such that I cannot contribute to outside the org. And reporting a bug seems to be considered as contributing.

What kind of information do you need? Datetime of when I try to filter for teams? Should I record a video if screenshot is not sufficient?

**Comment by nikhilgarg1047** [comment]
Hi @nooblucker- Sorry my bad. I meant if '_Only selected teams_' is selected, we show max. 100 teams by default. However, you can search for any required team. I tried to search for team and it worked for me. 

<img width="619" alt="Screenshot 2022-11-02 at 5 31 18 PM" src="https://user-images.githubusercontent.com/102305466/199486051-c8db4ccc-b518-414d-8baf-bdc66d484586.png">

It would be helpful if you can share the Datetime and recording as well when tried to filter for the teams.

**Comment by nooblucker** [comment]
@nikhilgarg1047 I tried it this morning, 2022-11-02_10h59_40
I posted a video on youtube: https://www.youtube.com/shorts/ILBgqnT8xnQ
I type in "codeowner", because there are multiple teams containing the word in their name. 
So the filtering does not work. It shows an error message "Optionen können derzeit nicht angezeigt werden."
When I remove all letters, I get the list of 100 teams, instead of 360. 
I can confirm by checking the DOM that there are 100 <li> objects for teams in the <ul>.

**Comment by nikhilgarg1047** [comment]
@nooblucker - I checked the logs and saw that the search API returned 403 (permission issue) status code. Hence, you are not seeing any search result. I'm still trying to figure out why it returned 403 as it is working fine for my test org. Just to confirm, are you facing this issue only for this org or other orgs as well? Also, are the other org members facing the same issue?

**Comment by nooblucker** [comment]
> @nooblucker - I checked the logs and saw that the search API returned 403 (permission issue) status code. Hence, you are not seeing any search result. I'm still trying to figure out why it returned 403 as it is working fine for my test org. Just to confirm, are you facing this issue only for this org or other orgs as well? Are the other org members facing the same issue? I'm assuming Github app is installed in the org and you are signed in to the channel.

I only have this one org. Other org members have the same problem. Yes GitHub app is installed and I am signed in.

It is also strange that I can get the list of 100 teams. So I am not sure why permissions should be not sufficient to get a subset of teams.

**Comment by nikhilgarg1047** [comment]
@nooblucker - To update, I'm able to reproduce the issue and will raise the PR to fix it.

**Comment by nikhilgarg1047** [comment]
@nooblucker - Can you please check now if you're able to select the teams or not?

**Comment by nooblucker** [comment]
> @nooblucker - Can you please check now if you're able to select the teams or not?

Thank you, it seems to work now!
