### ISSUE TITLE
Emoji movement is not working in desktop app version

### ISSUE THREAD

**Issue by dassusovan** [integrations/microsoft-teams#255]
**Describe the bug**
In web version when user hover the mouse/ send to user then user able to see the movement but when we used the desktop version then not able to see the movement 

**Expected behaviour**
It should be worked on both(web n desktop app versions).

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome 
 - Version will let you know the both versions( teams and chrome )

**Comment by nikhilgarg1047** [comment]
Hi @dassusovan - We post the same card for desktop and web app versions. I don't think this issue is related to GitHub integration with MS Teams and should be reported to Microsoft Teams platform.

**Comment by dassusovan** [comment]
Can you send me the link so I can post it there

**Comment by nikhilgarg1047** [comment]
I'm not sure but you can try to reach MS teams [here](https://support.microsoft.com/en-us/teams).
