### ISSUE TITLE
Unable to Do Anything Other Than Sign In and Sign Out

### ISSUE THREAD

**Issue by JosephTLyons** [integrations/microsoft-teams#26]
I've installed the extension into Teams and have linked my GitHub account to it, but I can't seem to do anything besides sign in and sign out.  I followed the examples for subscribing by using `@github subscribe...`, but it throws an error message: "Invalid command! Need some help with @github."  I then tried just `subscribe` and it stated "Sorry, this command is currently not supported in personal conversation scope. Try help," I then tried `help` and it only gave me the two options of signing in and signing out.  I'm not sure how to actually use this and the documentation doesn't seem to be uncovering anything for me.

**Comment by SonicGD** [comment]
I think you are doing this in app chat. But to subscribe you should do it in team channel.

**Comment by ashokirla** [comment]
@JosephTLyons: Yes, you can subscribe and perform all the actions in your channel. Today Personal app experience only supports signin and signout. Very soon, the rest of the commands will be supported.

**Comment by ashokirla** [comment]
We have fixed the documentation to mention about Personal app scope. Thanks a lot for your support.

**Comment by JosephTLyons** [comment]
Thanks, I'll give it a shot.
