### ISSUE TITLE
Subscriptions disappearing

### ISSUE THREAD

**Issue by garyc0221** [integrations/microsoft-teams#267]
**Describe the bug**
I have signed in to the plugin and subscribed to my organization. After 10 minutes or so I stop getting any updates into the channel, then when I run GitHub subscribe list it states Not subscribed to any repositories or accounts. Even though I was.

I may suspect this to be an issue with 2FA that I have on my GitHub and Microsoft account.

**To Reproduce**
1. Install GitHub app
2. Login to github account with 2fa
3. Subscribe to organization
4. Commit to main branch a couple times
5. Wait a bit
6. Run subscribe list

**Expected behavior**
It should always keep my subscriptions. 

**Desktop (please complete the following information):**
 - OS: Windows 10 Version	10.0.19043 Build 19043

You can see below the time stamps.

![image](https://user-images.githubusercontent.com/79464926/202225201-5ac1c8de-e717-48c8-91b7-bb1a350ba864.png)

**Comment by sanjeev9160** [comment]
@garyc0221 Was the app uninstalled from the repos? Also can you retry to re-subscribe it and observe it for couple of days. Also, GHES Private Preview is not required for it.

**Comment by garyc0221** [comment]
@sanjeev9160 I checked and the GitHub app is set to all repos and hasn't changed. I have resubscribed multiple times and it always stops working. It seems it stops working after a pull request that has an github action happening on it

**Comment by garyc0221** [comment]
@sanjeev9160 Im going to close this issue for now, it has been working as expected today.
