### ISSUE TITLE
Teams for GitHub is requesting "Read and Write access to Actions"

### ISSUE THREAD

**Issue by a-mnich** [integrations/microsoft-teams#270]
I just got a notifcation that the microsoft teams integration requested "Read and Write access to Actions".
  
I've read through the documented [GitHub permission scopes](https://github.com/integrations/microsoft-teams#github-permission-scopes) and there are neither permissions for actions nor any write permissions documented.

This is a bit unsettling as I currently do not know if this permission request was triggered by a user or why this permissions is needed at all. I don't want to grant any app write permissions when I dont' know what they are used for.

Could you provide any details on why these permissions are necessary?
In Addition it would be nice if you could at them to the documentation. :)
 
 
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/56564725/205035196-b413bd82-d247-4b7f-b9c9-02ab3514b350.png)

**Comment by eric-01001000** [comment]
We've got the same permissions update request.

**Comment by cjberg** [comment]
Same here. I'm guessing it's [related to this](https://github.com/integrations/microsoft-teams#upcoming-features-and-roadmap):

> GitHub Actions notifications and manage capabilities - Provide capabilities to run, view and manage workflows from chat. We are aiming to rollout this support by November 2022.

**Comment by ashokirla** [comment]
Hi 👋 

Today we have shipped Actions workflow notifications feature. If you want to use this feature, you need to grant permissions for your org to send Actions events.  More details about the feature can be found here: https://github.com/integrations/microsoft-teams#actions-workflow-notifications

**Comment by a-mnich** [comment]
Hi, 
thanks for the clarification and the updated documentation! - I guess everythings clear now. 😄
