### ISSUE TITLE
Unable to connect to github for authentication

### ISSUE THREAD

**Issue by MageshSrinivasulu** [integrations/microsoft-teams#278]
I am trying to create an action in my chatbot to connect with GitHub but for some reason, authentication doesn't seem to be happening.

Error:

![image](https://user-images.githubusercontent.com/79187874/208641969-894e5b20-f780-45af-91d7-d6c14674f0c8.png)

Stuck in the below URL

https://us.flow.microsoft.com/Content/static/Auth.html

![image](https://user-images.githubusercontent.com/79187874/208641851-36e08c20-7db9-4634-9e22-96f59575160e.png)

**Comment by nikhilgarg1047** [comment]
Hi @MageshSrinivasulu - We are a GitHub team that owns GitHub integration with MS Teams. This repo is for sharing feedback for GitHub app in Microsoft Teams. I don't think this issue is related to GitHub app integration.

**Comment by nikhilgarg1047** [comment]
Please reopen the issue if you think it is related to Github integration.
