### ISSUE TITLE
Can't connect Github with Teams for Home

### ISSUE THREAD

**Issue by avrabe** [integrations/microsoft-teams#286]
**Describe the bug**
i've installed the Teams app on github and started to connect to teams via teams.github.com.
Neither on my Mac nor on my Android phone I was able to get github into the teams app.

I'm using Teams for Home with my Office 365 subscription.
I've installed the Teams app into an organisation which I do share between the same members as my Office 365 subscription.

**Expected behavior**
Github integration to happen into Teams.

**Screenshots**
The android teams app says "Leider können Sie derzeit nicht zu diesem Ziel gebracht werden"
The Mac Teams app either to show a which window (shortly flickering) or a welcome to teams screen which does not progress (see below)

**Desktop (please complete the following information):**
 - M1 - Mac Ventura 13.1
 - Browser Edge
 - Version 13.1 (22C65)

**Smartphone (please complete the following information):**
 - Device: Pixel 7 pro
 - OS: Android 13
 - Browser Edge

<img width="990" alt="image" src="https://user-images.githubusercontent.com/10056645/213257322-13470440-4d68-4bc7-9bc5-cf799ce13345.png">

**Comment by avrabe** [comment]
Update:
Today I tried again and received following message:

**Das ausgewählte Benutzerkonto ist im Mandanten "Microsoft Services" nicht vorhanden und kann auf die Anwendung "1fec8e78-bce4-4aaf-ab1b-5451cc387264" in diesem Mandanten nicht zugreifen. Das Konto muss dem Mandanten zuerst als externer Benutzer hinzugefügt werden. Verwenden Sie ein anderes Konto.**

**Comment by shruti-shukla** [comment]
@avrabe 
This error looks like something on the teams platform and not related to the GitHub integration.
I found some links discussing a similar error you're seeing. https://community.spiceworks.com/topic/2292337-user-account-does-not-exist-in-tenant
Please reach out to MSTeams Support for help with this issue. Thanks!
