### ISSUE TITLE
How do we get started?

### ISSUE THREAD

**Issue by jjaimon** [integrations/microsoft-teams#30]
This is a query than an issue itself. [Readme.md](https://github.com/integrations/microsoft-teams/blob/master/Readme.md) states how to install Github(Preview) integration in Teams and how to connect that with your GitHub account.    How do we use this after the setup process?  As the document suggest, app channel supports only SignIn and SignOut.   

**Get Started** section states that `You can subscribe to get notifications for pull requests and issues for an Organization or Repository's activity using @github subscribe <organization>/<repository> command.`  Which channel do you give this command?  I sent this command in one of our Team channels but didn't get any responses.

Section also states `Before you subscribe, a Microsoft Teams app needs to be installed in GitHub and you need to grant access to the repositories`. It would be convenient if it hyperlinks to the app referred here.  You will find several apps in the marketplace for Microsoft Team Integration.  Which app is referred here?  Thank you for the help.

**Comment by ashokirla** [comment]
@jjaimon Thanks for the feedback. We will try to be a bit more clear in the documentation. To answer your question:
To start with, when you acquire the GitHub (Preview) app from Team app store, you need to choose which channel(s) you want to install the app to. 
- You can go to the channel where the app is installed and start subscribing to your repos.
- If you are not signed in, it will prompt to signin.
- Once you complete the signin, if you haven't installed the Teams app in GitHub, the bot prompts you to do so. 
![image](https://user-images.githubusercontent.com/25578249/92967444-e1df4900-f496-11ea-96d0-d052e6de7fb1.png)
We need authorization from user for bot to get info from GitHub. This is achieved through Teams app in GitHub. This is a one time activity and you can see all the apps installed in GitHub from your Organization settings -> Applications

- You can click on install app and it takes you to organizations list, select the org for your repo and then it will ask you to install the app and select the repositories. We recommend you to choose all repos unless you want to allow your team to subscribe to only specific repos.
![image](https://user-images.githubusercontent.com/25578249/92967726-64680880-f497-11ea-89d3-8cda0e0f6632.png)
- Once the installation is done, you will be redirected to teams and you will see the subscription is successful.
![image](https://user-images.githubusercontent.com/25578249/92967825-8b263f00-f497-11ea-99e2-bedb9f264a27.png)

**Comment by jjaimon** [comment]
@ashokirla thanks for the details.  I noticed the app is created by Microsoft Corporation.  I read in your blog that it is created by GitHub, so was wondering if I'm using the right one.
I was just `Add`ing the app. I get an option to `Add to a team` if I click on the dropdown and should have selected that.  

![image](https://user-images.githubusercontent.com/1941596/92986559-81253000-f4d9-11ea-87fd-bddac5bef523.png)

Thanks for the help.  I'm receiving notifications now.
![image](https://user-images.githubusercontent.com/1941596/92986860-62279d80-f4db-11ea-8320-af8eda132003.png)

**Comment by ashokirla** [comment]
@jjaimon The app is built and maintained by GitHub ChatOps team. It is published as an internal Microsoft Corporation app. This means you don't need to get additional approvals from your organizations to install this app. We are also getting M365 compliance attestation done. This means our GitHub app is a fully trusted and compliant app.
