### ISSUE TITLE
Unable to @mention the teams user

### ISSUE THREAD

**Issue by whereismyjetpack** [integrations/microsoft-teams#31]
In a team, if i type `@github subscribe repo` nothing happens, 

If I type `@` and arrow down to the Github (preview) user, a new issue modal pops up. I'm unable to interact with the user in my team..

![ezgif com-optimize](https://user-images.githubusercontent.com/3694886/92925969-553a7980-f409-11ea-808d-79c194e4f2ec.gif)

**Comment by holljen** [comment]
@github also does nothing for me also, I need to use @github (preview). 

I also had the issue you describe. I solved it by clicking the "right" (opposite of left) button on the popup instead of clicking it with the mouse. After that it worked similar to what you expect (at least it did for me).

**Comment by whereismyjetpack** [comment]
interesting when i type @github (preview) <space> the modal still pops up. @github (p then pushing the right arrow does nothing. I've tried with both the os x client, and the web client. If i type out @github (preview) and then manually enter a command it sends fine, but teams doesn't recognize @GitHub (Preview) as a user, and just shows up as plain text in the team chat.

**Comment by holljen** [comment]
Hmm... bizarre.. I have the behaviour that you describe in the personal conversation scope, but not in the channels. I am certain that I solved it with this right button solution but I can't replicate that any longer. In the personal conversation scope you of course do not have to prefix with @github.

**Comment by whereismyjetpack** [comment]
oddly enough, after one of my teamates interacts with the github user, i can! then in a new channel the same things happened.. so i'm wondering if there's something weirdo going on with my github, or teams account.

**Comment by ashokirla** [comment]
It is a Teams platform limitation that you cannot type @github command and run it directly. Teams expect you to select the bot to run the comment. The steps for running any bot command in Teams is as follows:
1. Start typing @ github and automatically the list of bots will show up.
2. You can click on tab to select the bot (GitHub (Preview)) or use mouse click.
3. Then you can either type the rest of the command or select the command from the suggestion list.
![image](https://user-images.githubusercontent.com/25578249/92966401-181bc900-f495-11ea-9f1b-ebed8364942c.png)
You will never have to type GitHub (Preview). And the preview tag will be removed once we go GA.

We have given this feedback to Teams platform to have support for passing the entire command instead of bot selection.

**Comment by whereismyjetpack** [comment]
@ashokirla  thanks for the feedback, the problem i'm seeing is that when i click, or tab i don't see those commands; i only see a "create new issue" modal pop-up

**Comment by holljen** [comment]
I have the exact same (sometimes)

**Comment by ashokirla** [comment]
That is weird. Probably something to do with your Teams setup. Can you try restarting your teams or check with any of your colleagues if they are facing the same issue on a consistent basis.

**Comment by whereismyjetpack** [comment]
Looks like some combination of uninstalling, restarting, and reinstalling fixed it in this channel.

**Comment by davetapley** [comment]
Same issue here, MacOS Mojave:
`You have Microsoft Teams Version 1.3.00.18164. It was last updated on 7/22/20`.

---

Side note: I had the 'old' extension ([this one](https://techcommunity.microsoft.com/t5/microsoft-teams-blog/github-code-better-together-with-github-and-microsoft-teams/ba-p/659444)) installed, I've uninstalled it and restarted Teams, but it still still shows up in autocomplete:

<img width="527" alt="autocomplete" src="https://user-images.githubusercontent.com/48232/92977139-0f010c80-f441-11ea-8efb-07fc0d97b29e.png">

---

Once I highlight **GitHub Preview**, regardless of whether I click on it, or <kbd>tab</kbd> or <kbd>enter</kbd>, this modal pops up:

<img width="525" alt="modal" src="https://user-images.githubusercontent.com/48232/92977243-57202f00-f441-11ea-99f5-a95a880c78eb.png">

**Comment by ashokirla** [comment]
@davetapley Can you also check if the old GitHub app is present in the personal scope or part of message extension.

**Comment by ashokirla** [comment]
@davetapley Are you still facing the issue. Can you try uninstalling the app, restart the teams and re-install it.

**Comment by mcg** [comment]
Having similar issues here. Have installed and reinstalled the Integration. The bot shows up in a channel but interaction with it don't do anything.The bot doesn't respond.

**Comment by brettcurtis** [comment]
@davetapley - were you able to remove the old one? I disabled it everywhere I know of and it still pops up!

**Comment by brettcurtis** [comment]
ohh jeesh, just found it under apps in the top level team... sorry..

**Comment by VincentLiu1** [comment]
**This may be helpful:**
I had the same issue. I then open "Manage Teams" for my team and went to the "Apps" tab. I didn't find the "GitHub (Preview)" from the list. So I just went to "More apps" from there and installed this app again. Now it works for me.

**Comment by gauravsaralMs** [comment]
following up with MsTeams team on this.

**Comment by davetapley** [comment]
@ashokirla 
> @davetapley Can you also check if the old GitHub app is present in the personal scope or part of message extension.

I don't know what "the personal scope or part of message extension" is? 😑 

> Are you still facing the issue. Can you try uninstalling the app, restart the teams and re-install it.

Yep, still present, I have tried reinstalling.

---


@brettcurtis  @VincentLiu1 this was a good find!
>  open "Manage Teams" for my team and went to the "Apps" tab

⬆️  I did this and the old app was still there 😱 
Unfortunately removing (and re-install the new one) still didn't fix the problem.

**Comment by ashokirla** [comment]
@davetapley , we will help you out with this issue. Can you lets us know if we can have a call sometime next week. We will look into your setup and see how to get it fixed.

**Comment by bondz** [comment]
I had this issue and I had to install the app in the specific team.

![github](https://user-images.githubusercontent.com/4683867/94089254-9c156f80-fe0a-11ea-8f52-cae9b8364ff1.gif)

**Comment by ashokirla** [comment]
@bondz yes, you need to install to specific team. When you click on just Add, it will only install personal chat bot where we only support signin and signout commands. And you dont need to use @ github when you are in personal chat. We will update the documentation to avoid this confusion.

**Comment by holljen** [comment]
Issue solved?
