### ISSUE TITLE
Notify for commits on branches other than the default one

### ISSUE THREAD

**Issue by RedaAouad** [integrations/microsoft-teams#32]
Hi,

All is in the title!
Any expected date for it?

**Comment by zhuberty** [comment]
I am also experiencing this issue exactly as stated.

**Comment by ashokirla** [comment]
Hi @RedaAouad , @zhuberty Thanks for sharing your feedback. Commits for all/any branch is in our backlog. We will work on it next quarter.

**Comment by borgendorf** [comment]
Thanks for clarifying. I thought I had done something wrong. The majority of check-in work in my group is done in branches. As you build this feature, please make sure to **list the name of the branch in the card.** The previous integration didn't do that and it caused several instances of confusion. Thanks, and keep up the good work. It's already nicer than the previous legacy one.

**Comment by ashokirla** [comment]
We have now shipped the support for filtering commits based on branches. 
Refer to: https://github.com/integrations/microsoft-teams/blob/master/Readme.md#branch-filters-for-commits
