### ISSUE TITLE
Checks report

### ISSUE THREAD

**Issue by laurentkempe** [integrations/microsoft-teams#33]
Hey, again thanks for this integration which will ease some work in my team 👍 👏 

I would like to know if you have some plan to add the Github Checks as something that would be reported in Teams?
For example, we have our CI build which is one check, and it would be fantastic to see it in Teams!

![image](https://user-images.githubusercontent.com/272612/92941257-6eb2e400-f450-11ea-9bc8-4bd8182b1a9d.png)

**Comment by ashokirla** [comment]
@laurentkempe It is already supported. After you subscribe to repo, any PR notification card will also report check status.
