### ISSUE TITLE
[question] what are the permissions needed by the app?

### ISSUE THREAD

**Issue by nadavsinai-philips** [integrations/microsoft-teams#370]
at both org and repo levels
I could not find this in the docs

**Comment by geramirez** [comment]
You can see the permission on at this URL - 
https://github.com/organizations/<your org>/settings/installations/

They may change based on the features we build - the current set is.

```
Permissions
 Read access to checks, code, commit statuses, deployments, discussions, members, and metadata
 Read and write access to actions, issues, and pull requests
```

GitHub will ask the org admin to update
