### ISSUE TITLE
Integration with Azure DevOps

### ISSUE THREAD

**Issue by JimGBritt** [integrations/microsoft-teams#38]
It would be great to have the ability to integrate Teams with Azure DevOps similar to how you've integrated GitHub with Teams.

**Comment by ashokirla** [comment]
@JimGBritt We already have integrations for Azure DevOps with Teams.
https://docs.microsoft.com/en-us/azure/devops/pipelines/integrations/microsoft-teams?view=azure-devops
https://docs.microsoft.com/en-us/azure/devops/repos/integrations/repos-teams?view=azure-devops
https://docs.microsoft.com/en-us/azure/devops/boards/integrations/boards-teams?view=azure-devops

**Comment by JimGBritt** [comment]
Excellent I will check it out. You can likely close this issue out. Thank you!
