### ISSUE TITLE
GitHub App not working in channels

### ISSUE THREAD

**Issue by likamrat** [integrations/microsoft-teams#393]
**Describe the bug**
The integration stopped working on channels but works when interacting with the app. Also tried creating a new channel for testing ended up with same issue.

**To Reproduce**
1. Connect the app to a channel
2. Use the standard app methods

**Expected behavior**
GitHub Teams integration to work back with channels.

**Screenshots**
#### Channel - not responding
![image](https://github.com/user-attachments/assets/a70c9d54-1fb1-4699-928f-47e8d8691363)
![image](https://github.com/user-attachments/assets/521df517-955f-4b16-aba2-1e53524c66b7)
![image](https://github.com/user-attachments/assets/f3f21346-3127-4e8e-8b5f-eb5f1803c9a3)

#### Direct interaction - working
![image](https://github.com/user-attachments/assets/c94e4698-33aa-4a07-86ae-97f4b740a10f)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Teams client version: 24295.602.3198.862
 
![image](https://github.com/user-attachments/assets/5b0c92d3-3ae5-4dca-b7c4-8068979444ba)

**Comment by omusavi** [comment]
+1, running into the same issue, all bot notifications stopped on 10/10/24

**Comment by likamrat** [comment]
It looks like no one is monitoring this issue 😭

**Comment by Roolingen** [comment]
+1. Works in chat, doesn't work in channels

**Comment by ndrewwm** [comment]
+1, integration works in 1:1 chats with the bot, but not in channels.

**Comment by leigholiver** [comment]
seeing the same here, it dropped for us on the 21st

**Comment by gionn** [comment]
> integration works in 1:1 chats with the bot

I setup review reminders on my 1:1, and they are still working, but not even `help` command is replying anymore - I cannot manage them anymore.

On channels it's completely dead (no scheduled reminders even if there are pending PR and no reactions to `help` or any other command).

> it dropped for us on the 21st

also for me, between 20-21 Nov

**Comment by gionn** [comment]
@leachj any chance you can reach anyone maintaining this integration in Microsoft?

**Comment by cassdeckard** [comment]
+1, this stopped working in our org some time after 11/22

**Comment by gionn** [comment]
Maybe there is a chance everything is correlated to https://www.reddit.com/r/microsoft/comments/1gzq7qc/megathread_mo941162_users_may_be_unable_to_access/

This night I have a bunch of scheduled reviews reminders popping up at midnight (they are not configured to run at midnight)

**Comment by cassdeckard** [comment]
OK so I was actually able to get this working again in my org, although I lost all my existing subscriptions and had to recreate them. To get the GitHub bot to start responding again, I had to go into an existing thread in the channel, hit the "+" button next to the send button in the reply UI:
![image](https://github.com/user-attachments/assets/9956ea28-a3bd-4791-b786-ec77f752c22f)
Search for "GitHub" and click on it, you'll get a dialog asking you to add the integration, click on Add. It will then ask you about creating a Pull Request but at that point you've fixed the integration so you can just close the dialog and go back to using chatbot commands like `subscribe`

**Comment by omusavi** [comment]
Thanks @cassdeckard that workaround worked for me!

**Comment by BeanBeam11** [comment]
@cassdeckard It finally worked!!! Thank you~~~~

**Comment by leigholiver** [comment]
@cassdeckard thanks! that worked here also

**Comment by ndrewwm** [comment]
You're a hero @cassdeckard! Thanks for surfacing this.

**Comment by likamrat** [comment]
Thank you so much @cassdeckard . Closing this for now.
