### ISSUE TITLE
Scheduled reminders not reminding

### ISSUE THREAD

**Issue by legrab** [integrations/microsoft-teams#404]
**Describe the bug**
The Scheduled Reminders in channels seem to be broken.

We last received notifications for Pending pull requests on 26th November.
All other notifications from Subscriptions work unchanged, only Schedules don't.

**To Reproduce**
1. Add Scheduled Reminder of pull requests to a teams channel via "@GitHub schedule myOrganization"
2. Setup time and allow all repositories, all teams, minimum age 2 hours
3. Wait for trigger time
4. Acknowledge nothing happens

**Expected behavior**
We had reminders scheduled that worked for months but they have become broken without any (known) actions taken to them.
We tried updating the existing reminders as well as deleting them and recreating them with wider settings, but to no avail.

**Screenshots**
![image](https://github.com/user-attachments/assets/b7eb8429-b13f-464e-ba35-a0c690fc7da2)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version of Teams: 24295.605.3225.8804

**Comment by PetoriousBIG** [comment]
I'm also seeing this behavior. The last time my scheduled reminder went off was 8AM EST, November 25. There haven't been any changes to the reminder since I set it up over a year ago. I edited it as a test and never received the reminder. 

- OS: Windows 11
- Verion of Teams: 24295.605.3225.8804

**Comment by Vnagy09** [comment]
Just wanted to confirm that I am also experiencing this. The scheduled reminder stopped working for some reason.

- OS: Windows 11
- Teams version: 24295.605.3225.8804

**Comment by yamengpeng** [comment]
I've also met this issue. The schedule stopped the reminder from 11/26.
- OS: macOS 15.1.1 (24B91)
- Teams Version: 24295.606.3238.6194

**Comment by MatthiasKrallinger** [comment]
Hey, I'm seeing the same behaviour as the guys already described.

- OS: Windows 11
- Teams version: 24295.605.3225.8804

**Comment by leachj** [comment]
MS Teams scheduled reminders are working again now, apologies for the outage.

**Comment by PetoriousBIG** [comment]
My 8 AM reminder just came in, thank you very much!
