### ISSUE TITLE
Unable to signin?

### ISSUE THREAD

**Issue by jepetty** [integrations/microsoft-teams#44]
Hi! Super excited to use this plugin, but for some reason I can't sign in :/ I've tried running the `@github signin` command from both the chat with the GitHub bot (screenshot included) and in another Teams channel. From within the chat, the bot responds that the command was invalid and then suggests I try the command `signin`.

![image](https://user-images.githubusercontent.com/10744199/93398732-f9b92300-f830-11ea-993f-3da3ef34ed62.png)

Can anyone see what I'm doing wrong?

**Comment by ashokirla** [comment]
@jepetty GitHub app can be installed for your team/channel as well as into you personal scope. What you see is personal chat. 
In personal chat, you don't have to type @github. As the help response suggests, just run `signin`. In Personal chat, today, we only support signin and signout. More functionalities will be added in future. 

You can also install the app for your team/channel by clicking on 'Add to a team'.
![image](https://user-images.githubusercontent.com/25578249/93421410-e6f52b80-f8ce-11ea-98ac-97463a40c290.png)
In the channel scope, we support all the features like subscriptions, customizations, notifications and create issue.

**Comment by ashokirla** [comment]
Closing this issue for now.
