### ISSUE TITLE
Button Rendering Template not rendered in the Browser

### ISSUE THREAD

**Issue by ajitjha393** [integrations/microsoft-teams#48]
Its show {{::buttonText }} at the navbar
I am able to click and it do gets redirected to the teams activity page
The only problem is There is no styling or actual text on the button

![image](https://user-images.githubusercontent.com/42679346/93856323-7edf8480-fcd6-11ea-9131-a9fcd74a5c07.png)

**Comment by ashokirla** [comment]
@gauravsaralMs Can you look into this query

**Comment by gauravsaralMs** [comment]
@ajitjha393 : can you please explain more on this issue?

@ashokirla : can you add a standard issue template on this repo? 
see this for example: https://github.com/microsoft/AdaptiveCards/issues/new/choose

**Comment by ajitjha393** [comment]
@gauravsaralMs 
I am currently using Ms teams for attending my college Lectures
So while using Ms teams in Browser , there are these different Sections in Navbar like Chats , assignments , meetings and so on

SImilarly there is a **teams** tab where in we can see all of our created teams 
So in that page , on the top instead of Showing **"Teams"** as the title ,it displays {{ ::buttonText }} template (.. I guess it is of vue string interpolation or pseudoSelector rendering) 

So basically the placeholder template is not replaced while browser rendering , the possible problem might be due to wrong variable declaration or ejs templating error (!not sure about this)


This is how the other tabs show the correct title : 
**Feed Tab**
![image](https://user-images.githubusercontent.com/42679346/93965429-c110d080-fd7f-11ea-8138-55368be8032d.png)

And title shown in case of Teams tab :
**Teams Tab**
![image](https://user-images.githubusercontent.com/42679346/93965519-f61d2300-fd7f-11ea-861a-f1f8dc35064d.png)

**Comment by ajitjha393** [comment]
I couldn't find Ms teams github repo 
But came across this repo
so notified it here !

**Comment by gauravsaralMs** [comment]
sure, thanks @ajitjha393 .. 
@ashokirla can you work with partner team to get required attention on this issue?

**Comment by ashokirla** [comment]
Informed the Partner team to look into this issue.

**Comment by ajitjha393** [comment]
The issue has been resolved now !
