### ISSUE TITLE
@github pops up the issue creation window without letting me type a command

### ISSUE THREAD

**Issue by johnpage-agixis** [integrations/microsoft-teams#54]
**Describe the bug**

**To Reproduce**
1. Add the Github preview app
2. Sign in
3. Go to a channel
4. Type @github and see Github preview suggested
5. Click on the suggestion or use the tab key

**Expected behavior**
I expect to see **Github (Preview)** in the text entry box with the possibility to continue typing a command, but instead the text entry box shows **Github (Preview)** for an instant, then empties and the issue creation window opens up.

**Screenshots**

![2020-09-29 09_03_23-AgiDevs _ Microsoft Teams](https://user-images.githubusercontent.com/62235266/94524248-a8e2fa80-0232-11eb-9f6a-98715e85c1b0.png)

**Desktop (please complete the following information):**
 - OS: Windows in french (France)
 - Teams app in french
 - Version (in Aide -> Nouveautés there is mention of updates from the 11th September)

**Smartphone (please complete the following information):**
Not tried

**Additional context**

**Comment by gauravsaralMs** [comment]
Thanks for reporting the issue @johnpage-agixis .

can you please 
1. share the screenshot of what are you seeing when you are trying to type `@github` ?  Do you get suggested commands?

2. can you make sure that when installing you are using the `add to a team` option
![image](https://user-images.githubusercontent.com/43203065/94641113-f8dac380-02fd-11eb-9696-f2b530c4362e.png)

**Comment by johnpage-agixis** [comment]
I didn't add it to a team, I'll try that.

This is what I get when I type @github
![image](https://user-images.githubusercontent.com/62235266/94689478-3572e300-032f-11eb-88ac-1fef61d20c39.png)

**Comment by gauravsaralMs** [comment]
@johnpage-agixis : please let us know your experience post `add it to a team`.

I suspect that to be the issue and once that is determined we will work with teams platform team to evaluate improvement options.

**Comment by johnpage-agixis** [comment]
TLRD; It seems to work, and I hope using @github commands inside conversations will soon be possible

I added it to a team, then tried using @github commands in a conversation, but that didn't work.2
I added a canal to the team and I successfully subscribed to a repo therein.

**Comment by gauravsaralMs** [comment]
@ashokirla : is this something we need to fix with documentation? product is behaving as expected...

thanks @johnpage-agixis , we will try to improve the experience here.

**Comment by johnpage-agixis** [comment]
Well, I had read that it only worked in Canals and not in chats, but in my team we rarely use canals, because switching between canals and chats requires a click or two too many - we just use group conversations.

So that was a source of confusion, but other than that, I have to admit it worked as announced.

**Comment by gauravsaralMs** [comment]
@johnpage-agixis : will it be fine if we can close this issue?
