### ISSUE TITLE
Typo when announcing successful installation 

### ISSUE THREAD

**Issue by orta** [integrations/microsoft-teams#55]
**To Reproduce**

Install the GitHub App:

![Screen Shot 2020-09-30 at 8 08 55 AM](https://user-images.githubusercontent.com/49038/94683101-f5dad580-02f3-11eb-8437-175795ac5aa0.png)

**Expected behavior**
Github -> GitHub

**Comment by gauravsaralMs** [comment]
Thanks a lot for reporting this

**Comment by gauravsaralMs** [comment]
@orta :  This should be fixed now, thanks a lot for reporting this issues.
