### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by administradoresavoristravelio** [integrations/microsoft-teams#58]
**Describe the bug**
No repository found with error: "Please check to make sure the spelling of the resource was correct and that you have access to the resource in GitHub".

**To Reproduce**
1. Go to a channel and type @github subscribe org/repo
2. See error "Please check to make sure the spelling of the resource was correct and that you have access to the resource in GitHub"

<img width="970" alt="image" src="https://user-images.githubusercontent.com/72024914/94895995-cdd2aa00-048c-11eb-918c-428be95da96f.png">

**Expected behavior**
Repo notifications enabled

**Desktop (please complete the following information):**
 - OS: mac OS 10.15.7
 - Browser: Safari
 - macOS Teams Version App: 1.3.00.18164

**Additional context**
Microsoft Teams App installed on GitHub as owner and enabled for all repositories.
<img width="764" alt="image" src="https://user-images.githubusercontent.com/72024914/94895963-b8f61680-048c-11eb-9dc0-b831490b1da7.png">

Login is ok:

<img width="970" alt="image" src="https://user-images.githubusercontent.com/72024914/94896026-dfb44d00-048c-11eb-9993-5dbefdf1bb38.png">

Repository name is correct:

<img width="539" alt="image" src="https://user-images.githubusercontent.com/72024914/94896113-06728380-048d-11eb-8328-29856629246b.png">

**Comment by gauravsaralMs** [comment]
@administradoresavoristravelio , can you please try @bondz suggestion?

**Comment by administradoresavoristravelio** [comment]
Hi. Thanks! After re-login it works.
