### ISSUE TITLE
Issue opened/closed notifications posted to Teams sporadically

### ISSUE THREAD

**Issue by sblomberg** [integrations/microsoft-teams#59]
**Describe the bug**
After successfully configuring GitHub -> Microsoft Teams (Public Preview) to a channel, the `issue` subscription works very sporadically. It seemed to work better after the initial installation, but less than half the time now (a week after install).

**To Reproduce**
1. Install GitHub (Preview) to organization
2. `signin` to connect GitHub account to app
3. Add GitHub (Preview) to desired team
4. In desired channel, `@github subscribe <my/repo> issues`
5. See issue opened/closed notifications only occasionally posted to my channel

**Expected behavior**
I expect issue opened/closed notifications to post to my channel 100% of the time.

**Screenshots**
Signed-in after installing to organization:

![image](https://user-images.githubusercontent.com/2219531/95259720-3bfcd100-07ed-11eb-8b08-5be17a2e33e6.png)

Added to team:

![image](https://user-images.githubusercontent.com/2219531/95259765-4e770a80-07ed-11eb-8b08-00d4d6137aa3.png)

Showing active subscription to issues, attempting to resubscribe with no change in flaky behavior:

![image](https://user-images.githubusercontent.com/2219531/95259970-972ec380-07ed-11eb-81a9-327994fb5f04.png)

GitHub integrations page:

![image](https://user-images.githubusercontent.com/2219531/95260169-e543c700-07ed-11eb-847b-d2e7744f213f.png)

Showing one of the working notifications between several issue opens/closes that were not reported:

![image](https://user-images.githubusercontent.com/2219531/95260488-69964a00-07ee-11eb-87da-29f1ad71197e.png)

**Desktop:**
 - OS: macOS Catalina
 - Microsoft Teams Desktop client
 - Version Version 1.3.00.24758

**Smartphone:**
n/a

**Additional context**
Happy to provide organization- or installation-specific details upon request.

**Comment by gauravsaralMs** [comment]
@sblomberg : just to confirm, from the same repository you are some times getting issue notification and some times not getting issue notification?

**Comment by sblomberg** [comment]
@gauravsaralMs Correct, this same repository and team is sometimes getting issue notifications and sometimes not.

**Comment by sblomberg** [comment]
It appears that the GitHub (Preview) integration is most often missing issue opened/closed notifications when those issues have been closed via another third-party integration using the GitHub API. When we open/close issues manually via the GitHub online interface, the GitHub (Preview) integration works as expected.

**Comment by gauravsaralMs** [comment]
@sblomberg : apologies for the late response. we actually pushed some fixes around this..
are you still seeing this issue?

**Comment by sblomberg** [comment]
@gauravsaralMs It might be getting better, but it's still not 100%. In the last 3 days, we've had 10 new issues opened on our issues repository at https://github.com/roastar-inc/roastar-issues/issues (issues 1192-1201). Of those ten issues, only 7 were posted in our Teams channel. All three issues that were skipped by the GitHub Teams integration were posted to the GitHub issues project via an API.

Is there anything we need to do to get these recent fixes in our Teams channel? As of today it appears that we're on version 1.3.

![image](https://user-images.githubusercontent.com/2219531/113308286-a3429c00-92cb-11eb-90eb-a9e87df9f039.png)

**Comment by sblomberg** [comment]
@gauravsaralMs The issues that the Microsoft Teams integration is skipping all appear to have backslashes in the title. Maybe those backslashes need to be escaped before sending from GitHub to Teams?

Here's an example of an issue title that is NOT getting sent to Teams: `UploadToS3Error in App\Jobs\UploadToS3`

**Comment by gauravsaralMs** [comment]
@sblomberg : Thanks for pointing to the exact issue @sblomberg .
we will try to fix this ASAP

**Comment by masayyad** [comment]
@sblomberg, the fix for this issue has been released. Thanks for reaching us. Please feel free to reopen if the issue still persists.
