### ISSUE TITLE
Cannot subscribe to repository

### ISSUE THREAD

**Issue by krzysztof-magosa** [integrations/microsoft-teams#64]
**Describe the bug**
Cannot subscribe to repository

**To Reproduce**
1. Add App to Teams channel
2. Type @github subscribe organisation/repository

**Expected behavior**
I expect integration to be subscribed to repository

**Actual behavior**
Could not find resource organisation/repository.
Please check to make sure the spelling of the resource was correct and that you have access to the resource in GitHub.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 1.3.00.24758

**Comment by gauravsaralMs** [comment]
@krzysztof-magosa , can you try these 2 things?
- can you try subscribe with url to repository
- if your repo is behind SSO then can you try to sign-out and sign-in again and giving SSO access in the flow?

**Comment by krzysztof-magosa** [comment]
Hi @gauravsaralMs.
Seems it was SSO thing.
Previously when I was logging into GitHub from Teams it didn't ask me for SSO.
Now it did, I authorised app to access organisation and successfully subscribed!
Thanks a lot.
