### ISSUE TITLE
Teams screen sharing doesn't work for receivers when monitor display is set to portrait mode.

### ISSUE THREAD

**Issue by nisar-philips** [integrations/microsoft-teams#65]
**Describe the bug**
Teams screen sharing doesn't work for receivers when monitor display is set to portrait mode.

**To Reproduce**
0. Pre-requisite: Set monito display as portrait mode.
1. Go to Teams
2. Click on Screen Share
3. Error: receiver unable to see screen properly.

**Expected behavior**
Screen share should work seamlessly.

**Screenshots**
I don't have the screenshot. Hope, the replication steps mentioned above will help the team.

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: App
 - Version: 1.3.00.24755 (64-bit).

**Comment by gauravsaralMs** [comment]
👋 @nisar-philips : This is not looking something related to teams and github integration.
May be you are looking for https://microsoftteams.uservoice.com/

**Comment by gauravsaralMs** [comment]
please reopen if issue is with teams and github integration
