### ISSUE TITLE
Cannot subscribe to repository

### ISSUE THREAD

**Issue by luh2** [integrations/microsoft-teams#67]
Hi, 

I installed the app in both Teams and GitHub. When I install it in GitHub on my personal space, it works well on public repositories.

But if I install it in an organization, that is enforcing SSO to our Azure AD tenant, and the repository is private or public, I get the message in Teams 

     Could not find resource org/repository
     Please check to make sure the spelling of the resource was correct and that you have access to the resource in GitHub.

when I try to ATGitHub subscribe org/repository. 

Is this a known bug?

**Comment by gauravsaralMs** [comment]
can you try to sign-out and sing-in again ?
if app is installed on the org which is backed by SSO then in the signin flow you should see option to select org SSO .

**Comment by luh2** [comment]
Worked! It would be nice, if this could be documented somewhere or works out of the box. Irritating when trying it at first. Thanks.
