### ISSUE TITLE
Can't create issue

### ISSUE THREAD

**Issue by luh2** [integrations/microsoft-teams#68]
Hi,

I might be simply too stupid, but I get

Either the Teams GitHub app is not installed on your repository or the repository doesn't exist. Install the app to proceed further.
Note: You need to be an organization owner to install the app.

when I try to create an issue, despite it being installed. Any idea on why that could be, or is that a bug? Happens both to a public repository and a private one.

Cheers,

**Comment by ashokirla** [comment]
@luh2 Can you share a snapshot of the issue.

**Comment by luh2** [comment]
Ok, so here are the

**Comment by luh2** [comment]
The issue happens only on private repositories in SSO connected organizations. 
- app is installed 
- logged in and out again (as was needed with another SSO integration)
- then logging in, subscribing. both successful
![image](https://user-images.githubusercontent.com/2047083/97149610-4a476880-176d-11eb-8bd9-de6c2a78643a.png)
- then trying to create a test issue, this message pops up
![image](https://user-images.githubusercontent.com/2047083/97149714-6814cd80-176d-11eb-87ea-afe3225d049d.png)

**Comment by ashokirla** [comment]
@gauravsaralMs can you look into this issue.

**Comment by gauravsaralMs** [comment]
@luh2 : just to be clear..
you are trying to create issue in the same repo which you have subscribed to?

and if possible can you also share the snapshot of what you are filling in the create issue dialog which pops up?

**Comment by DivyankaM** [comment]
@luh2 : Could you please check the following-

i. The organization/repo combination exists.
ii. You have sufficient permissions to create the issue on that repo.
iii. GitHub app is installed on the concerned repo (You already confirmed on this, just mentioning for the checklist).

**Comment by luh2** [comment]
Thanks you two. I did check and all is good. It was a language barrier. I thought owner was meant to be the owner of the ticket, not the owner of the repository. That's why it worked on the personal one.
