### ISSUE TITLE
Does this work under SSO?

### ISSUE THREAD

**Issue by chrisyates-sage** [integrations/microsoft-teams#7]
Hi,

I've followed the installation instructions, and I have administrative access to our organisation (and enterprise) so I have installed the app there. When I try to subscribe to a repo in an organisation that has had SAML SSO enabled, the error message is:

_

> Could not find resource xxx/xxxx
> Please check to make sure the spelling of the resource was correct and that you have access to the resource in GitHub.

_

but I can subscribe to one of my own private repos. Just wondered if it's the SSO that is stopping this request going through, or something else?

Chris.

**Comment by divais** [comment]
Thank you for sharing Chris, we are looking into it and will get back. I am assuming you have admin rights on the organisation, correct?

**Comment by chrisyates-sage** [comment]
Yes that's correct, full organisation owner rights.

**Comment by gauravsaralMs** [comment]
@chrisyates-sage : can you try to signout then signin..
and then try to subscribe again?

please note that signout is a disruptive process so it will remove all subscriptions which you have already created.

Other option is that someone in your team who has access to the repo and has not signed in into teams app can try to signin and subscribe

**Comment by chrisyates-sage** [comment]
Thank you, that did indeed solve the problem - signing out and signing back in, and re-subscribing. I think there was an authorization page that showed this time around that wasn't displayed to me the first time. All working now!

**Comment by ashokirla** [comment]
@chrisyates-sage How are you :).

First of all, thanks a lot for your support.
As its been more than a month since we released our private preview. We would like to hear your experience and learn about any feedback. 

Also, we are currently working on rolling out public beta and we would like to share our features and get them validated. Can you let us know if we can have a quick call?

**Comment by bondz** [comment]
Wow! This should be in an easy to find place. In the readme for example.

I had this exact issue and I've been trying all day. Signing out and signing in fixed it 👍
