### ISSUE TITLE
Bot does not pick up approval on PR

### ISSUE THREAD

**Issue by simia** [integrations/microsoft-teams#70]
**Describe the bug**
Bot does not report that PR has been approved. It completely ignores review comments as well.
Normal comments under the PR are reported as expected.

**To Reproduce**
Make a PR. Make a Review of that PR with comments.

**Expected behavior**
I expect to get notifications about review comments and review outcome (reject/approve)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise. 10.0.19041
 - Browser Ms Edge

**Additional context**
Not sure if this is relevant but PR was created before the bot was installed.

**Comment by gauravsaralMs** [comment]
@simia : can you share if you see this same flow for PRs which were created post app installtion?

**Comment by simia** [comment]
New PRs do not work as expected as well.
First and second (review) comment is ignored by the bot. Third one is posted on the teams.

![image](https://user-images.githubusercontent.com/7147203/98351301-cf0f6d80-201c-11eb-8a34-822d93b99654.png)

**Comment by apurva1112** [comment]
> **Describe the bug**
> Bot does not report that PR has been approved. It completely ignores review comments as well.
> Normal comments under the PR are reported as expected.
> 
> **To Reproduce**
> Make a PR. Make a Review of that PR with comments.
> 
> **Expected behavior**
> I expect to get notifications about review comments and review outcome (reject/approve)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows 10 Enterprise. 10.0.19041
> * Browser Ms Edge
> 
> **Additional context**
> Not sure if this is relevant but PR was created before the bot was installed.

@simia Please confirm that you are subscribed to reviews to see review comments and approvals/rejections.
Please use `subscribe user/repo reviews` to subscribe to reviews for a repo.

See the below image for example
![image](https://user-images.githubusercontent.com/42499837/98365913-25020680-2059-11eb-9428-6853daa64f0b.png)

**Comment by simia** [comment]
This resolved the issue. I was not subscribed for reviews. Assumed that subscribe user/repo subscribes for everything. Thank you!

**Comment by gauravsaralMs** [comment]
@simia : if all looks good, can we resolve/close this issue?
