### ISSUE TITLE
Profile image of the person is not consistently displayed while typing in Microsoft teams

### ISSUE THREAD

**Issue by vishnuprakash9845** [integrations/microsoft-teams#73]
**Describe the bug**
**Other person profile image will be displayed when chatting in teams,

**Person B profile image will be displayed when Person A is chatting to me.****

_I am not in Group chart when I observed this bug, and there are no people with same name and profile image._

**To Reproduce**
1. Start your chart with Person B
2. Again switch your chart with Person A
3. Now when Person A is typing the message you will see the Person B profile image for some time

**Expected behavior**
I expect when some is messaging or chatting in teams their exact profile image should de displayed

**Screenshots**
_Adding the screenshot_
![image](https://user-images.githubusercontent.com/24207575/99772264-74076b80-2b30-11eb-87dd-2bb6a1df67d0.png)

_Microsoft Teams version_
![image](https://user-images.githubusercontent.com/24207575/99772568-060f7400-2b31-11eb-84c6-12f444a62553.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise Version 1909 (OS build 18363.1139)
 - Browser : NA
 - Version Version 1909 (OS build 18363.1139)
 - Microsoft Teams Version [1.3.00.28779]

**Additional context**
Referring to screenshot
**I chatted with Mr Persona B, then I switched to Persona A[...Pradeep], when persona A is typing I can see Person B profile image. Which is not expected right?**

**Comment by gauravsaralMs** [comment]
@vishnuprakash9845 : can you please confirm if this is something related to github and teams integration?

**Comment by vishnuprakash9845** [comment]
> @vishnuprakash9845 : can you please confirm if this is something related to github and teams integration?

@gauravsaralMs  I am not sure on this github and teams integration. I am using Microsoft Teams for office purpose and observed this small bug kind of so raised the issue in this platform.

**Comment by gauravsaralMs** [comment]
@vishnuprakash9845 : this repository is for tracking teams and github integration issues..
I will suggest you to use: https://microsoftteams.uservoice.com/forums/555103-public-preview

**Comment by vishnuprakash9845** [comment]
> @vishnuprakash9845 : this repository is for tracking teams and github integration issues..
> I will suggest you to use: https://microsoftteams.uservoice.com/forums/555103-public-preview

Thank you @gauravsaralMs , I have raised the issue on the forum.

**Comment by gauravsaralMs** [comment]
Closing this one
