### ISSUE TITLE
Comments to issues are not published in the teams conversations

### ISSUE THREAD

**Issue by nrafal** [integrations/microsoft-teams#74]
**Describe the bug**
I can subscribe to a private repository within organization, and I can see issues being created. GitHub bot also comments correctly when issue is closed or reopened. Unfortunately, no comments are added to a issue thread. 

**To Reproduce**
I can reproduce it on every channel in different teams - whenever I add GitHub (Preview) I can see issues, bot no comments despite subscribing to it.

**Expected behavior**
I expect comments correctly appear in issue's thread.

**Screenshots**
![image](https://user-images.githubusercontent.com/9462330/100994195-a2d10900-3556-11eb-9b3f-39cb83eae76c.png)
![image](https://user-images.githubusercontent.com/9462330/100994266-b41a1580-3556-11eb-895f-778d240f3a72.png)
![image](https://user-images.githubusercontent.com/9462330/100994342-c72ce580-3556-11eb-92a0-ec581705bf2b.png)
![image](https://user-images.githubusercontent.com/9462330/100994395-d3b13e00-3556-11eb-9e91-937d024c7381.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: no applicable

**Additional context**
This is a private repository. App is installed in team on GitHub, and have access to all repositories.

**Comment by sushmita-m** [comment]
@nrafal fixed this on prod, can you check now?

**Comment by nrafal** [comment]
Working as advertised - thanks!
