### ISSUE TITLE
Dependentbot card shows html code, not rendered html content

### ISSUE THREAD

**Issue by xqliu** [integrations/microsoft-teams#75]
**Describe the bug**
Dependentbot card shows html code  rather than rendered html content in the card, can refer to the follow for a screenshot.

  * Actual behaviour: Dependentbot card shows html code  rather than rendered html content in the card
  * Expect behaviour: Ideally I think it should display similar as what shown on PR in github PR page.

* Teams card

![Screenshot 2020-12-08 at 10 08 25 AM](https://user-images.githubusercontent.com/22554/101429538-25364000-393e-11eb-883c-9f5cbb3e2dc3.png)

* Github PR page

<img width="1092" alt="Screenshot 2020-12-08 at 10 11 10 AM" src="https://user-images.githubusercontent.com/22554/101429360-bbb63180-393d-11eb-9210-b9d6545baf4a.png">

**Comment by xqliu** [comment]
Duplicate with #41

**Comment by gauravsaralMs** [comment]
@xqliu : given that this is dup of https://github.com/integrations/microsoft-teams/issues/41, will it be fine if we close this issue?
I will recommend you to put your comment in #41 only, so that #41 can be prioritised..

**Comment by xqliu** [comment]
Sure thanks.
