### ISSUE TITLE
Subscribe to all repositories in a GitHub organization

### ISSUE THREAD

**Issue by PathogenDavid** [integrations/microsoft-teams#77]
**Is your feature request related to a problem? Please describe.**

My GitHub organization has low enough activity that subscribing to every repo in the organization is reasonable, but it has a lot of (smaller) repos I'd like to subscribe to to help keep an eye on them. Manually subscribing to them all was fairly tedious, and in the future I'm worried I'd miss adding a new project by mistake.

**Describe the solution you'd like**

Allow subscribing to an entire organization. Maybe `@github subscribe MyOrganization/*`. This would subscribe the channel to every repo in the specified organization, including new ones as they're created.

Ideally it'd be nice to be able to opt-out of specific repositories too.

**Describe alternatives you've considered**

Manually subscribing to each project one at a time. (Which is pretty clunky and tedious.)

**Additional context**

N/A

**Comment by jwfuller** [comment]
@PathogenDavid I think `@github subscribe MyOrganization` will sub you to the entire org

**Comment by PathogenDavid** [comment]
@jwfuller Thanks! That does indeed appear to work.
