### ISSUE TITLE
Support for compact messages

### ISSUE THREAD

**Issue by masterzen** [integrations/microsoft-teams#8]
Hi,

I haven't tested the official integration apps for MS Teams and GitHub yet, so what follows comes only from reading the README.

Coming from Slack to MS Teams, we've found that the current unofficial GitHub integration is taking a very large amount of screen real estate on each message. Looking at the screenshots in the README, it also seems that the cards sent can be large.

On the other hand, the official GitHub Slack integration produces very compact messages (even when opening a new PR), for instance this one:

<img width="769" alt="Screenshot 2020-07-01 at 18 14 24" src="https://user-images.githubusercontent.com/20242/86267487-11382680-bbc7-11ea-80d4-bac48b271948.png">

One reason we haven't activated the unofficial integration available in the Teams App Store yet, is because of a lack of compact cards.

Thanks for considering my feature request :)

**Comment by ashokirla** [comment]
@masterzen Thanks for your feedback and support. The reason we provided detailed cards is to provide additional context like reviewers, labels, etc. We are planning to introduce threading where any successive activities on the Issue or PR like close, reopen, comments etc. will be appended to the card as a reply with compact info. This way user can have all the context when you see a post. 

I have couple of questions:
When you say compact, what is the basic information you would like to see in the card.
Would threading solve your problem.

It would be great if we can have a call so that we can share our plan and get it validated.

**Comment by masterzen** [comment]
Hi @ashokirla,

Many thanks for your answer.
I'm not sure threading (while being very nice) is a solution for our use case. When a new reply would arrive on a PR post, it would immediately make the PR post current (ie going on the bottom of the Teams window). Since the first post might be large, it gets in the way of the other chat posts in the channel (especially on small laptop screens).

What makes Teams card tall IMHO are the facts block. It is a very space consuming, and information could be displayed in a much more terse way.

The minimum information I'd like to have in a "compact" main PR post is:
* PR Number & title (as link so that I can easily click on it)
* Optionally the very beginning of the PR message
* Optionally Labels
* Requested Reviewers

The way things are displayed are IMHO important. For instance if you look at this Slack card:

<img width="685" alt="Screenshot 2020-07-15 at 17 43 43" src="https://user-images.githubusercontent.com/20242/87566850-d7d1e180-c6c3-11ea-8dd4-6f96d88084ca.png">

It just shows the important information (albeit it displays the PR text which in this case was only one line). The labels & reviewers are shown on the same line which is a compact way for displaying information.

The thing is, interested users wanting to know more or needing to act on the PR would anyway click on the link, so it might not be needed to actually list all the PR content in the post. Maybe if the integration would support a reply command that would allow to ask for subsequent information (ie full message, diffstats, etc), then only the interested people would use it without spamming the whole channel with unneeded information to most of the other users.

Now compare the Slack integration with the "unofficial" GitHub Teams integration (sorry it's not the same PR, and I know that what you want to build is very different):
<img width="809" alt="Screenshot 2020-07-15 at 17 58 13" src="https://user-images.githubusercontent.com/20242/87567912-203dcf00-c6c5-11ea-8776-19ff600434fc.png">

If you look at this example it represents all that can be wrong in an information card design. There are 5 facts (the PR didn't had any message otherwise it would have been displayed) taking a large amount of space, among which the number of commits, head, base and number of files, which I doubt are interesting to anyone. This only adds noise. The PR number is a facts, it could have been in the card notification title, the date also has no interest since the message already has a timestamp. And while there are great chances I'll click on the _View in GitHub_, the other buttons could just be reply commands.

When looking to the screenshots in https://github.com/integrations/microsoft-teams/blob/master/docs/Microsoft%20Teams%20for%20GitHub.md, it is much better than the current unofficial integration I posted a screenshot of above. There is still information that might not be needed at first glance (ie complete message, diff stats). And in general anything that is presented in facts could be represented differently to take less space and be as usable.

Of course, our use case is maybe not what most people would want :)
But what I've seen so far about Teams is that more people asking for a more compact Teams UI, with the idea that more information can be displayed with less wasted free space. The teams UI can only show a small amount of channel messages on small laptop screens (ie 13" or 14"), and the teams UI becomes unusable when new large messages pops up, flushing the messages you were reading three pages up...

I think I'm going to install the integration as soon I'll get the permissions to install custom apps in our Teams. That way I will be able to deliver a more constructive feedback.

I'd love to have a chat, but I'll be away for the next couple of weeks for vacations.

Many thanks for reading my ticket,
--
Brice

**Comment by ashokirla** [comment]
Hi @masterzen,

Thanks a lot for your feedback. This is very helpful. As we are currently working public preview, I would like to share our plans and validated with you. This would be a great opportunity for us to incorporate any feedback at design time itself. 

Can you let me know if we can have a quick sync up sometime next week.

Thanks,
Ashok.

**Comment by ashokirla** [comment]
@masterzen We have rolled out our public beta. Your insights are very helpful. We have ensured our notification post experience is as crisp as possible.

Closing this issue for now. Please keep sharing feedback.
