### ISSUE TITLE
Wrong icon in Audio settings

### ISSUE THREAD

**Issue by Diego-MX** [integrations/microsoft-teams#81]
**Description**
When setting up audio configuration in Kubuntu 20.10 using Plasma 5.19, I see Skype icon instead of MS-Teams icons. 

**Steps to reproduce**
1. Open MS-Teams application. 
2. Go to: 
    a) System Settings > Audio > Applications. 
    b) System Tray > Audio notifications. 
3. See Skype icon instead of MS-Teams icon. 

**Expected behavior**
I see MS-Teams icon since that's the application I'm interested in. 

**Screenshots**
![msteams-audio-settings](https://user-images.githubusercontent.com/9877444/103664633-17bda700-4f38-11eb-9f11-888a164d073d.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.10
 - Plasma 5.19

**Additional context**
Let me know if you need other context.

**Comment by gauravsaralMs** [comment]
This feedback should go to https://microsoftteams.uservoice.com/.

This repository is for tracking issues with respect to GitHub and teams integration.
