### ISSUE TITLE
Specify to only receive Dependabot pull requests

### ISSUE THREAD

**Issue by Alexander-Betz** [integrations/microsoft-teams#86]
Hello, a small question: Is it possible to get notifications in a Teams channel for only pull requests that are created by Github's Dependabot and not all pull requests?
I don't see an option in the documentation but maybe I'm missing it.

Thanks in advance for any answer.

**Comment by ashokirla** [comment]
If you have any labels added when a dependabot creates PRs, you can use the label to filter your notifications.
https://github.com/integrations/microsoft-teams/blob/master/Readme.md#label-filters-for-issues-and-prs

**Comment by smlgbl** [comment]
Is there a way to exclude based on labels instead? We would like to exclude dependabot PRs, not specifically include them...
