### ISSUE TITLE
GitHub + Microsoft Teams private preview 

### ISSUE THREAD

**Issue by ashokirla** [integrations/microsoft-teams#9]
I am creating this issue to track the requests for private preview for our new GitHub app for Microsoft Teams. 

How do I participate in Private Preview?
Very simple, just follow the steps mentioned [here](https://github.com/integrations/microsoft-teams/blob/master/Readme.md).

What can I do with this app?
You can subscribe to your GitHub Repos or accounts and get notifications for PRs and Issues. More features are being added.

What if I have any feedback?
We are currently working on adding more functionalities to this app and any feedback about your experience with the app is very much appreciated. If you are interested in understanding more about our plans and backlog, please let us know. We are more than happy to discuss over a call.

**Comment by lucasweijers** [comment]
Hi Ashokirla, my name is Lucas and i am a developer at [fonQ](https://www.fonq.nl) and we currently integrated GitHub in Microsoft Teams with this project.

We are curious about your plans, timeline and backlog and we would like to have a call and discuss the future of this project.
We also have some good suggestions and feedback. You can contact me at lucas.weijers@fonq.nl and then we can plan a meeting / video call

Kind regards,
Lucas Weijers
Developer at [fonQ](https://www.fonq.nl)

**Comment by ashokirla** [comment]
@lucasweijers, Thanks a lot for your interest. I am happy to setup a call and share our plans. I have sent you an email for the same.

**Comment by ashokirla** [comment]
We have now rolled out public preview of GitHub app to Teams app store. And we are closing private preview. Thanks everyone for your support. 
For more details, checkout: https://github.com/integrations/microsoft-teams/blob/master/Readme.md
