### ISSUE TITLE
App Not Found Error

### ISSUE THREAD

**Issue by jaydeland** [integrations/microsoft-teams#99]
**To Reproduce**
Trying to add this integration leads to an App not found error message

**Expected behavior**
App installs

**Comment by gauravsaralMs** [comment]
@jaydeland : can you please share some more details like the steps followed and the error you are seeing?
sharing screen shots will also help us a lot

**Comment by gauravsaralMs** [comment]
@jaydeland : gentle ping

**Comment by jaydeland** [comment]
JIRA for Server installs: https://teams.microsoft.com/l/app/6eacb5f0-68b0-46f0-9507-9e906c6861fc

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/9366595/113581692-7d800480-95f5-11eb-8528-3fa41b26ac50.png">

**Comment by gauravsaralMs** [comment]
@jaydeland : is this about JIRA app ?

This repo is for GitHub app in Teams marketplace
https://teams.microsoft.com/l/app/ca9e26b7-dce5-44a0-b2b7-a70a3d65ce25

**Comment by jaydeland** [comment]
@gauravsaralMs - Yes this is for integration with our JIRA server

**Comment by gauravsaralMs** [comment]
@jaydeland : This repo is to track github integration with MsTeams

If you are looking for github integration with Jira then please reach out to https://github.com/integrations/jira
If you are looking for MsTeams integration with Jira then I am not sure where you can raise this issue.
